"""identity and structure (M1)

SPEC 3.3 and 4.3's identity and structure blocks: fourteen tables, plus two foreign keys
M0 deliberately deferred to this revision.

app/models/audit.py said so in its own docstring -- "actor_person_id and
actor_identity_id are plain UUIDs with no foreign key: they reference person and
auth_identity, which M1 owns. M1's revision adds the constraints once the tables they
point at exist." app/models/studio.py said the same about created_by_identity_id.
Autogenerate cannot infer either, because the model columns carry no constraint to
detect, so both are written by hand below.

No GRANT statements. Revision 0001 set `ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT
SELECT, INSERT, UPDATE, DELETE ON TABLES TO studio_app`, so every table this revision
creates inherits the runtime grant. tests/identity/test_migration.py asserts that
actually happened per table rather than trusting it did -- and asserts 0002's REVOKE on
audit_log still stands, because a revision that touches that table must not quietly
re-grant what 0002 took away.

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-25

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_identity',
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_private_relay', sa.Boolean(), nullable=False),
    sa.Column('linked_to_identity_id', sa.UUID(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_developer', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['linked_to_identity_id'], ['auth_identity.id'], name=op.f('fk_auth_identity_linked_to_identity_id_auth_identity'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_identity')),
    sa.UniqueConstraint('provider', 'provider_subject', name=op.f('uq_auth_identity_provider_provider_subject'))
    )
    op.create_index('ix_auth_identity_email', 'auth_identity', ['email'], unique=False)
    op.create_table('oauth_transaction',
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('code_verifier', sa.Text(), nullable=False),
    sa.Column('redirect_uri', sa.String(length=500), nullable=False),
    sa.Column('app', sa.String(length=16), nullable=False),
    sa.Column('return_path', sa.String(length=200), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_transaction')),
    sa.UniqueConstraint('state', name=op.f('uq_oauth_transaction_state'))
    )
    op.create_table('auth_revocation',
    sa.Column('auth_identity_id', sa.UUID(), nullable=False),
    sa.Column('sessions_issued_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auth_identity_id'], ['auth_identity.id'], name=op.f('fk_auth_revocation_auth_identity_id_auth_identity'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_revocation'))
    )
    op.create_index('ix_auth_revocation_auth_identity_id', 'auth_revocation', ['auth_identity_id'], unique=False)
    op.create_table('platform_admin',
    sa.Column('auth_identity_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auth_identity_id'], ['auth_identity.id'], name=op.f('fk_platform_admin_auth_identity_id_auth_identity'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_admin')),
    sa.UniqueConstraint('auth_identity_id', name=op.f('uq_platform_admin_auth_identity_id'))
    )
    op.create_table('class',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discipline', sa.String(length=60), nullable=True),
    sa.Column('color', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_class_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class'))
    )
    op.create_index('ix_class_studio_id_id', 'class', ['studio_id', 'id'], unique=False)
    op.create_index('uq_class_studio_id_name', 'class', ['studio_id', 'name'], unique=True)
    op.create_table('health_form_template',
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_pdf_object_key', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("kind IN ('full', 'trial')", name=op.f('ck_health_form_template_health_form_template_kind')),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_health_form_template_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_form_template'))
    )
    op.create_index('ix_health_form_template_studio_id_id', 'health_form_template', ['studio_id', 'id'], unique=False)
    op.create_index('uq_health_form_template_kind_version', 'health_form_template', ['studio_id', 'kind', 'version'], unique=True)
    op.create_table('location',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_location_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location'))
    )
    op.create_index('ix_location_studio_id_id', 'location', ['studio_id', 'id'], unique=False)
    op.create_table('person',
    sa.Column('auth_identity_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('photo_object_key', sa.String(length=500), nullable=True),
    sa.Column('locale', sa.String(length=8), nullable=True),
    sa.Column('anonymized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['auth_identity_id'], ['auth_identity.id'], name=op.f('fk_person_auth_identity_id_auth_identity'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_person_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person'))
    )
    op.create_index('ix_person_auth_identity_id', 'person', ['auth_identity_id'], unique=False)
    op.create_index('ix_person_studio_id_email', 'person', ['studio_id', 'email'], unique=False)
    op.create_index('ix_person_studio_id_id', 'person', ['studio_id', 'id'], unique=False)
    op.create_index('ix_person_studio_id_phone', 'person', ['studio_id', 'phone'], unique=False)
    op.create_table('refresh_token',
    sa.Column('auth_identity_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('active_studio_id', sa.UUID(), nullable=True),
    sa.Column('acting_as_person_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['active_studio_id'], ['studio.id'], name=op.f('fk_refresh_token_active_studio_id_studio'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['auth_identity_id'], ['auth_identity.id'], name=op.f('fk_refresh_token_auth_identity_id_auth_identity'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_token_token_hash'))
    )
    op.create_index('ix_refresh_token_auth_identity_id', 'refresh_token', ['auth_identity_id'], unique=False)
    op.create_index('ix_refresh_token_family_id', 'refresh_token', ['family_id'], unique=False)
    op.create_table('group',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('age_min IS NULL OR age_max IS NULL OR age_min <= age_max', name=op.f('ck_group_group_age_range')),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], name=op.f('fk_group_class_id_class'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_group_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group'))
    )
    op.create_index('ix_group_studio_id_id', 'group', ['studio_id', 'id'], unique=False)
    op.create_index('uq_group_class_id_name', 'group', ['class_id', 'name'], unique=True)
    op.create_table('guardian',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('relation', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_guardian_person_id_person'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_guardian_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guardian')),
    sa.UniqueConstraint('student_id', 'person_id', name=op.f('uq_guardian_student_id_person_id'))
    )
    op.create_index('ix_guardian_studio_id_id', 'guardian', ['studio_id', 'id'], unique=False)
    op.create_index('ix_guardian_studio_id_person_id', 'guardian', ['studio_id', 'person_id'], unique=False)
    op.create_index('uq_guardian_one_primary_per_student', 'guardian', ['student_id'], unique=True, postgresql_where=sa.text('is_primary'))
    op.create_table('invitation',
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('intended_role', sa.String(length=20), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_person_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("intended_role IN ('owner', 'manager', 'lead_coach', 'assistant_coach', 'guardian')", name=op.f('ck_invitation_invitation_intended_role')),
    sa.CheckConstraint('email IS NOT NULL OR phone IS NOT NULL', name=op.f('ck_invitation_invitation_has_a_recipient')),
    sa.ForeignKeyConstraint(['accepted_by_person_id'], ['person.id'], name=op.f('fk_invitation_accepted_by_person_id_person'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_invitation_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitation')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_invitation_token_hash'))
    )
    op.create_index('ix_invitation_studio_id_email', 'invitation', ['studio_id', 'email'], unique=False)
    op.create_index('ix_invitation_studio_id_id', 'invitation', ['studio_id', 'id'], unique=False)
    op.create_table('role_assignment',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('scope_type', sa.String(length=10), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('granted_by_person_id', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'manager', 'lead_coach', 'assistant_coach')", name=op.f('ck_role_assignment_role_assignment_role')),
    sa.CheckConstraint("scope_type IN ('studio', 'class', 'group')", name=op.f('ck_role_assignment_role_assignment_scope_type')),
    sa.ForeignKeyConstraint(['granted_by_person_id'], ['person.id'], name=op.f('fk_role_assignment_granted_by_person_id_person'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_role_assignment_person_id_person'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_role_assignment_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_assignment'))
    )
    op.create_index('ix_role_assignment_studio_id_id', 'role_assignment', ['studio_id', 'id'], unique=False)
    op.create_index('ix_role_assignment_studio_id_person_id', 'role_assignment', ['studio_id', 'person_id'], unique=False)
    op.create_index('uq_role_assignment_live', 'role_assignment', ['studio_id', 'person_id', 'role', 'scope_type', sa.literal_column("COALESCE(scope_id, '00000000-0000-0000-0000-000000000000'::uuid)")], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('uq_role_assignment_one_live_owner', 'role_assignment', ['studio_id'], unique=True, postgresql_where=sa.text("role = 'owner' AND revoked_at IS NULL"))
    op.create_table('group_staff',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("role IN ('lead_coach', 'assistant_coach')", name=op.f('ck_group_staff_group_staff_role')),
    sa.CheckConstraint('to_date IS NULL OR to_date >= from_date', name=op.f('ck_group_staff_group_staff_date_range')),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('fk_group_staff_group_id_group'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_group_staff_person_id_person'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_group_staff_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_staff'))
    )
    op.create_index('ix_group_staff_studio_id_id', 'group_staff', ['studio_id', 'id'], unique=False)
    op.create_index('ix_group_staff_studio_id_person_id', 'group_staff', ['studio_id', 'person_id'], unique=False)
    op.create_index('uq_group_staff_live', 'group_staff', ['group_id', 'person_id'], unique=True, postgresql_where=sa.text('to_date IS NULL'))
    op.add_column('studio', sa.Column('created_by_identity_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_studio_created_by_identity_id_auth_identity'), 'studio', 'auth_identity', ['created_by_identity_id'], ['id'], ondelete='RESTRICT')

    # Deferred out of M0 and named in app/models/audit.py. Autogenerate cannot see
    # these: the model columns are plain UUIDs with no ForeignKey to detect, which is
    # exactly how M0 was able to create audit_log before person and auth_identity
    # existed.
    op.create_foreign_key(
        'fk_audit_log_actor_person_id_person',
        'audit_log', 'person', ['actor_person_id'], ['id'], ondelete='RESTRICT',
    )
    op.create_foreign_key(
        'fk_audit_log_actor_identity_id_auth_identity',
        'audit_log', 'auth_identity', ['actor_identity_id'], ['id'], ondelete='RESTRICT',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_audit_log_actor_identity_id_auth_identity', 'audit_log', type_='foreignkey'
    )
    op.drop_constraint('fk_audit_log_actor_person_id_person', 'audit_log', type_='foreignkey')
    op.drop_constraint(op.f('fk_studio_created_by_identity_id_auth_identity'), 'studio', type_='foreignkey')
    op.drop_column('studio', 'created_by_identity_id')
    op.drop_index('uq_group_staff_live', table_name='group_staff', postgresql_where=sa.text('to_date IS NULL'))
    op.drop_index('ix_group_staff_studio_id_person_id', table_name='group_staff')
    op.drop_index('ix_group_staff_studio_id_id', table_name='group_staff')
    op.drop_table('group_staff')
    op.drop_index('uq_role_assignment_one_live_owner', table_name='role_assignment', postgresql_where=sa.text("role = 'owner' AND revoked_at IS NULL"))
    op.drop_index('uq_role_assignment_live', table_name='role_assignment', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index('ix_role_assignment_studio_id_person_id', table_name='role_assignment')
    op.drop_index('ix_role_assignment_studio_id_id', table_name='role_assignment')
    op.drop_table('role_assignment')
    op.drop_index('ix_invitation_studio_id_id', table_name='invitation')
    op.drop_index('ix_invitation_studio_id_email', table_name='invitation')
    op.drop_table('invitation')
    op.drop_index('uq_guardian_one_primary_per_student', table_name='guardian', postgresql_where=sa.text('is_primary'))
    op.drop_index('ix_guardian_studio_id_person_id', table_name='guardian')
    op.drop_index('ix_guardian_studio_id_id', table_name='guardian')
    op.drop_table('guardian')
    op.drop_index('uq_group_class_id_name', table_name='group')
    op.drop_index('ix_group_studio_id_id', table_name='group')
    op.drop_table('group')
    op.drop_index('ix_refresh_token_family_id', table_name='refresh_token')
    op.drop_index('ix_refresh_token_auth_identity_id', table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index('ix_person_studio_id_phone', table_name='person')
    op.drop_index('ix_person_studio_id_id', table_name='person')
    op.drop_index('ix_person_studio_id_email', table_name='person')
    op.drop_index('ix_person_auth_identity_id', table_name='person')
    op.drop_table('person')
    op.drop_index('ix_location_studio_id_id', table_name='location')
    op.drop_table('location')
    op.drop_index('uq_health_form_template_kind_version', table_name='health_form_template')
    op.drop_index('ix_health_form_template_studio_id_id', table_name='health_form_template')
    op.drop_table('health_form_template')
    op.drop_index('uq_class_studio_id_name', table_name='class')
    op.drop_index('ix_class_studio_id_id', table_name='class')
    op.drop_table('class')
    op.drop_table('platform_admin')
    op.drop_index('ix_auth_revocation_auth_identity_id', table_name='auth_revocation')
    op.drop_table('auth_revocation')
    op.drop_table('oauth_transaction')
    op.drop_index('ix_auth_identity_email', table_name='auth_identity')
    op.drop_table('auth_identity')
    # ### end Alembic commands ###
