"""w2 schedule and people (M2 || M3)

SPEC 4.3's "Structure and schedule" and "Students and guardians" blocks: twelve tables,
six from app/models/schedule.py and six from app/models/people.py. W2's contract commit,
authored on main before either worktree exists -- a lane never runs `alembic revision`.

`registration_request.payload_encrypted` is EncryptedJSON and not JSONB (11.1). An
unapproved registration is a stranger's personal data about a minor sitting in a queue,
encrypted before anyone in the studio has agreed to receive it. Writing the underlying
type instead would produce a working schema and a permanently dirty `alembic check`. The
type and its AAD are rendered by `_render_item` in alembic/env.py, added in this commit:
autogenerate's own rendering drops the required `aad` argument and the import, and the
revision raises TypeError the first time it runs.

`student.current_belt_id` and `student.price_plan_id` are plain UUID columns with no
foreign key, deliberately: belt_rank and price_plan are W4's tables and do not exist yet.
Both model docstrings say so. W4's contract commit adds the ForeignKey to the two MODEL
columns and lets autogenerate emit the ALTERs; hand-writing a constraint the models do not
declare leaves test_the_migrations_match_the_models red forever on a schema that is
actually correct.

Two columns here exist because of the club's real structure, recorded as C11 and C12:

  enrollment.attends_weekdays -- which of a group's weekly sessions a student is expected
  at (5.7). A group trains twice a week; a student may come once. Without this they are
  absent_unexcused every week forever and read as 50 percent attendance while attending
  everything they agreed to. NULL means "all of them" and is the common case.

  student.price_plan_id -- the tuition price, per STUDENT (5.10). It is not on enrollment,
  and that is the whole of C11: the club prices by how often a child trains, not by which
  groups they attend, so a child in two groups is one charge rather than two. `charge`'s
  idempotency index is keyed on student_id for the same reason, in W4's revision.

No GRANT statements. Revision 0001 set `ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT
SELECT, INSERT, UPDATE, DELETE ON TABLES TO studio_app`, so every table this revision
creates inherits the runtime grant. This revision does not touch audit_log, so 0002's
REVOKE stands untouched.

Both partial unique indexes keep their `postgresql_where`, and both are load-bearing.
`uq_enrollment_live` without `ended_on IS NULL` becomes a total unique constraint and a
student can never re-enrol in a group they once left; `uq_training_year_one_active`
without `status = 'active'` allows one training year per studio, ever.

W3 to W5's models are NOT here. They sit in app/models/_pending/, out of Base.metadata,
until each wave's own contract commit moves its files up and autogenerates 0007 to 0009.

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-25

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.core.encryption

# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_year',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'active', 'closed')", name=op.f('ck_training_year_training_year_status')),
    sa.CheckConstraint('ends_on > starts_on', name=op.f('ck_training_year_training_year_date_range')),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_training_year_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_year'))
    )
    op.create_index('ix_training_year_studio_id_id', 'training_year', ['studio_id', 'id'], unique=False)
    op.create_index('uq_training_year_one_active', 'training_year', ['studio_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_index('uq_training_year_studio_id_name', 'training_year', ['studio_id', 'name'], unique=True)
    op.create_table('registration_request',
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('payload_encrypted', app.core.encryption.EncryptedJSON('registration_request.payload_encrypted'), nullable=False),
    sa.Column('matched_person_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_by_person_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("source IN ('public_link', 'parent_app', 'manager')", name=op.f('ck_registration_request_registration_request_source')),
    sa.CheckConstraint("status = 'pending' OR reviewed_at IS NOT NULL", name=op.f('ck_registration_request_registration_request_review_recorded')),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name=op.f('ck_registration_request_registration_request_status')),
    sa.ForeignKeyConstraint(['matched_person_id'], ['person.id'], name=op.f('fk_registration_request_matched_person_id_person'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_person_id'], ['person.id'], name=op.f('fk_registration_request_reviewed_by_person_id_person'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_registration_request_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registration_request'))
    )
    op.create_index('ix_registration_request_studio_id_id', 'registration_request', ['studio_id', 'id'], unique=False)
    op.create_index('ix_registration_request_studio_id_status', 'registration_request', ['studio_id', 'status'], unique=False)
    op.create_table('student',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('joined_on', sa.Date(), nullable=True),
    sa.Column('left_on', sa.Date(), nullable=True),
    sa.Column('current_belt_id', sa.UUID(), nullable=True),
    sa.Column('health_status', sa.String(length=15), nullable=False),
    sa.Column('price_plan_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("health_status IN ('missing', 'trial_signed', 'signed')", name=op.f('ck_student_student_health_status')),
    sa.CheckConstraint("status IN ('lead', 'trial', 'pending_approval', 'active', 'frozen', 'left', 'lost')", name=op.f('ck_student_student_status')),
    sa.CheckConstraint('left_on IS NULL OR joined_on IS NULL OR left_on >= joined_on', name=op.f('ck_student_student_membership_range')),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_student_person_id_person'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_student_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student')),
    sa.UniqueConstraint('person_id', name=op.f('uq_student_person_id'))
    )
    op.create_index('ix_student_studio_id_id', 'student', ['studio_id', 'id'], unique=False)
    op.create_index('ix_student_studio_id_status', 'student', ['studio_id', 'status'], unique=False)
    op.create_table('studio_closure',
    sa.Column('training_year_id', sa.UUID(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("source IN ('holiday_preset', 'manual')", name=op.f('ck_studio_closure_studio_closure_source')),
    sa.CheckConstraint('date_to >= date_from', name=op.f('ck_studio_closure_studio_closure_date_range')),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_studio_closure_studio_id_studio'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['training_year_id'], ['training_year.id'], name=op.f('fk_studio_closure_training_year_id_training_year'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_studio_closure'))
    )
    op.create_index('ix_studio_closure_studio_id_id', 'studio_closure', ['studio_id', 'id'], unique=False)
    op.create_index('ix_studio_closure_training_year_id_date_from', 'studio_closure', ['training_year_id', 'date_from'], unique=False)
    op.create_table('enrollment',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('started_on', sa.Date(), nullable=False),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.Column('attends_weekdays', postgresql.ARRAY(sa.SmallInteger()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'active', 'frozen', 'ended')", name=op.f('ck_enrollment_enrollment_status')),
    sa.CheckConstraint('attends_weekdays IS NULL OR (array_length(attends_weekdays, 1) > 0 AND attends_weekdays <@ ARRAY[0,1,2,3,4,5,6]::smallint[])', name=op.f('ck_enrollment_enrollment_attends_weekdays')),
    sa.CheckConstraint('ended_on IS NULL OR ended_on >= started_on', name=op.f('ck_enrollment_enrollment_date_range')),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('fk_enrollment_group_id_group'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_enrollment_student_id_student'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_enrollment_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollment'))
    )
    op.create_index('ix_enrollment_group_id_status', 'enrollment', ['group_id', 'status'], unique=False)
    op.create_index('ix_enrollment_studio_id_id', 'enrollment', ['studio_id', 'id'], unique=False)
    op.create_index('ix_enrollment_studio_id_status', 'enrollment', ['studio_id', 'status'], unique=False)
    op.create_index('uq_enrollment_live', 'enrollment', ['student_id', 'group_id'], unique=True, postgresql_where=sa.text('ended_on IS NULL'))
    op.create_table('group_schedule_rule',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_group_schedule_rule_group_schedule_rule_effective_range')),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_group_schedule_rule_group_schedule_rule_time_range')),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name=op.f('ck_group_schedule_rule_group_schedule_rule_weekday')),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('fk_group_schedule_rule_group_id_group'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_group_schedule_rule_location_id_location'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_group_schedule_rule_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_schedule_rule'))
    )
    op.create_index('ix_group_schedule_rule_group_id_weekday', 'group_schedule_rule', ['group_id', 'weekday'], unique=False)
    op.create_index('ix_group_schedule_rule_studio_id_id', 'group_schedule_rule', ['studio_id', 'id'], unique=False)
    op.create_table('student_freeze',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_by_person_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('to_date IS NULL OR to_date >= from_date', name=op.f('ck_student_freeze_student_freeze_date_range')),
    sa.ForeignKeyConstraint(['created_by_person_id'], ['person.id'], name=op.f('fk_student_freeze_created_by_person_id_person'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_student_freeze_student_id_student'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_student_freeze_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_freeze'))
    )
    op.create_index('ix_student_freeze_student_id_from_date', 'student_freeze', ['student_id', 'from_date'], unique=False)
    op.create_index('ix_student_freeze_studio_id_id', 'student_freeze', ['studio_id', 'id'], unique=False)
    op.create_table('student_status_history',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('changed_by_person_id', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_person_id'], ['person.id'], name=op.f('fk_student_status_history_changed_by_person_id_person'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_student_status_history_student_id_student'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_student_status_history_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_status_history'))
    )
    op.create_index('ix_student_status_history_student_id_changed_at', 'student_status_history', ['student_id', 'changed_at'], unique=False)
    op.create_index('ix_student_status_history_studio_id_changed_at', 'student_status_history', ['studio_id', 'changed_at'], unique=False)
    op.create_index('ix_student_status_history_studio_id_id', 'student_status_history', ['studio_id', 'id'], unique=False)
    op.create_table('session',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('training_year_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('is_manually_edited', sa.Boolean(), nullable=False),
    sa.Column('generated_from_rule_id', sa.UUID(), nullable=True),
    sa.Column('cancel_reason', sa.String(length=200), nullable=True),
    sa.Column('is_ad_hoc', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status <> 'cancelled' OR cancel_reason IS NOT NULL", name=op.f('ck_session_session_cancel_reason_required')),
    sa.CheckConstraint("status IN ('scheduled', 'cancelled', 'completed')", name=op.f('ck_session_session_status')),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_session_session_time_range')),
    sa.ForeignKeyConstraint(['generated_from_rule_id'], ['group_schedule_rule.id'], name=op.f('fk_session_generated_from_rule_id_group_schedule_rule'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('fk_session_group_id_group'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_session_location_id_location'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_session_studio_id_studio'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['training_year_id'], ['training_year.id'], name=op.f('fk_session_training_year_id_training_year'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session'))
    )
    op.create_index('ix_session_group_id_starts_at', 'session', ['group_id', 'starts_at'], unique=False)
    op.create_index('ix_session_studio_id_id', 'session', ['studio_id', 'id'], unique=False)
    op.create_index('ix_session_studio_id_starts_at', 'session', ['studio_id', 'starts_at'], unique=False)
    op.create_table('session_note',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('author_person_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_person_id'], ['person.id'], name=op.f('fk_session_note_author_person_id_person'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], name=op.f('fk_session_note_session_id_session'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_session_note_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_note'))
    )
    op.create_index('ix_session_note_session_id_created_at', 'session_note', ['session_id', 'created_at'], unique=False)
    op.create_index('ix_session_note_studio_id_id', 'session_note', ['studio_id', 'id'], unique=False)
    op.create_table('session_staff',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_substitute', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("role IN ('lead_coach', 'assistant_coach')", name=op.f('ck_session_staff_session_staff_role')),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_session_staff_person_id_person'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], name=op.f('fk_session_staff_session_id_session'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_session_staff_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_staff'))
    )
    op.create_index('ix_session_staff_studio_id_id', 'session_staff', ['studio_id', 'id'], unique=False)
    op.create_index('ix_session_staff_studio_id_person_id', 'session_staff', ['studio_id', 'person_id'], unique=False)
    op.create_index('uq_session_staff_session_id_person_id', 'session_staff', ['session_id', 'person_id'], unique=True)
    op.create_table('trial_booking',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('booked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attended', sa.Boolean(), nullable=True),
    sa.Column('outcome', sa.String(length=12), nullable=True),
    sa.Column('coach_note', sa.Text(), nullable=True),
    sa.Column('is_override', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("outcome IS NULL OR outcome IN ('pending', 'converted', 'lost')", name=op.f('ck_trial_booking_trial_booking_outcome')),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('fk_trial_booking_group_id_group'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], name=op.f('fk_trial_booking_session_id_session'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_trial_booking_student_id_student'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_trial_booking_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trial_booking'))
    )
    op.create_index('ix_trial_booking_student_id', 'trial_booking', ['student_id'], unique=False)
    op.create_index('ix_trial_booking_studio_id_booked_at', 'trial_booking', ['studio_id', 'booked_at'], unique=False)
    op.create_index('ix_trial_booking_studio_id_id', 'trial_booking', ['studio_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trial_booking_studio_id_id', table_name='trial_booking')
    op.drop_index('ix_trial_booking_studio_id_booked_at', table_name='trial_booking')
    op.drop_index('ix_trial_booking_student_id', table_name='trial_booking')
    op.drop_table('trial_booking')
    op.drop_index('uq_session_staff_session_id_person_id', table_name='session_staff')
    op.drop_index('ix_session_staff_studio_id_person_id', table_name='session_staff')
    op.drop_index('ix_session_staff_studio_id_id', table_name='session_staff')
    op.drop_table('session_staff')
    op.drop_index('ix_session_note_studio_id_id', table_name='session_note')
    op.drop_index('ix_session_note_session_id_created_at', table_name='session_note')
    op.drop_table('session_note')
    op.drop_index('ix_session_studio_id_starts_at', table_name='session')
    op.drop_index('ix_session_studio_id_id', table_name='session')
    op.drop_index('ix_session_group_id_starts_at', table_name='session')
    op.drop_table('session')
    op.drop_index('ix_student_status_history_studio_id_id', table_name='student_status_history')
    op.drop_index('ix_student_status_history_studio_id_changed_at', table_name='student_status_history')
    op.drop_index('ix_student_status_history_student_id_changed_at', table_name='student_status_history')
    op.drop_table('student_status_history')
    op.drop_index('ix_student_freeze_studio_id_id', table_name='student_freeze')
    op.drop_index('ix_student_freeze_student_id_from_date', table_name='student_freeze')
    op.drop_table('student_freeze')
    op.drop_index('ix_group_schedule_rule_studio_id_id', table_name='group_schedule_rule')
    op.drop_index('ix_group_schedule_rule_group_id_weekday', table_name='group_schedule_rule')
    op.drop_table('group_schedule_rule')
    op.drop_index('uq_enrollment_live', table_name='enrollment', postgresql_where=sa.text('ended_on IS NULL'))
    op.drop_index('ix_enrollment_studio_id_status', table_name='enrollment')
    op.drop_index('ix_enrollment_studio_id_id', table_name='enrollment')
    op.drop_index('ix_enrollment_group_id_status', table_name='enrollment')
    op.drop_table('enrollment')
    op.drop_index('ix_studio_closure_training_year_id_date_from', table_name='studio_closure')
    op.drop_index('ix_studio_closure_studio_id_id', table_name='studio_closure')
    op.drop_table('studio_closure')
    op.drop_index('ix_student_studio_id_status', table_name='student')
    op.drop_index('ix_student_studio_id_id', table_name='student')
    op.drop_table('student')
    op.drop_index('ix_registration_request_studio_id_status', table_name='registration_request')
    op.drop_index('ix_registration_request_studio_id_id', table_name='registration_request')
    op.drop_table('registration_request')
    op.drop_index('uq_training_year_studio_id_name', table_name='training_year')
    op.drop_index('uq_training_year_one_active', table_name='training_year', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_training_year_studio_id_id', table_name='training_year')
    op.drop_table('training_year')
    # ### end Alembic commands ###
