"""w4 billing events belts (M6 || M7)

SPEC 4.3's billing ledger, events and belts: seventeen tables from three model files
promoted out of app/models/_pending/ in W4's contract commit, authored on main before
either worktree exists -- a lane never runs `alembic revision`.

**This is the wave where invariant 1 stops being vacuous.** Every money column in the
product arrives here and every one of them is `*_agorot INTEGER` (G2). NUMERIC(10,2)
looks more responsible and is still wrong: a parent's balance has to agree with the
receipt they were handed, and it does that only if money is counted rather than measured.
`upay_ipn_record.amount` is the one deliberate exception and it is `String(30)`, not a
number at all -- uPay's inbound rendering kept byte-for-byte as evidence of what actually
arrived, because the IPN carries no cryptographic signature (SPEC 12) and the evidence is
the whole defence. `tests/invariants/test_01_money_is_never_a_float.py` exempts it by
qualified name so that no OTHER table's `amount` inherits the exemption.

**charge's idempotency index is keyed on student_id, not enrollment_id** -- conflict C11.
`uq_charge_student_period_kind` is UNIQUE on (student_id, period_year, period_month, kind),
partial on `student_id IS NOT NULL AND period_year IS NOT NULL`. The club prices by how
often a child trains, not by which groups they attend, so a child in two groups is ONE
tuition charge. Keying on the enrollment is precisely the defect C11 was raised to remove.
It is partial because only periodic charges have a period and a manual charge may
legitimately repeat; lose the predicate and a manager can raise exactly one manual charge
per family, ever.

**Two foreign keys W2 deferred land here, and both are on `student`.** `belt_rank` and
`price_plan` did not exist in W2, and a ForeignKey string is resolved at
mapper-configuration time, so writing either one then would have failed every test in the
suite rather than one. `student.current_belt_id` references `belt_rank.id` ON DELETE SET
NULL -- a studio reorganising its ladder is ordinary, and the grading history in
`student_belt` survives the demotion. `student.price_plan_id` references `price_plan.id`
ON DELETE RESTRICT, and the asymmetry is deliberate: a student silently losing their price
is a student the monthly run skips, which surfaces as a family nobody billed. Both are
ALTERs rather than inline constraints because `student` has existed since 0005.

**The payment / upay_ipn_record cycle is real, not a modelling slip.** Both directions are
SPEC 4.3 columns: `payment.upay_ipn_id` says which IPN produced a payment, and
`upay_ipn_record.matched_payment_id` records the reconciliation. It is resolved with
`use_alter=True` and an EXPLICIT constraint name on the reconciliation side, and both
halves matter -- without use_alter SQLAlchemy drops both constraints from its topological
sort and emits CREATE TABLEs Postgres rejects; without the explicit name Alembic cannot
write the DROP in downgrade(). This bites only on a FRESH database, so a run against an
existing one proves nothing about it.

Revision ID: 0008
Revises: 0007
Create Date: 2026-08-26 12:12:05.819088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, Sequence[str], None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_run',
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('charges_created', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status IN ('running', 'completed', 'failed')", name=op.f('ck_billing_run_billing_run_status')),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_billing_run_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_run'))
    )
    op.create_index('ix_billing_run_studio_id_id', 'billing_run', ['studio_id', 'id'], unique=False)
    op.create_index('uq_billing_run_studio_period', 'billing_run', ['studio_id', 'period_year', 'period_month'], unique=True)
    op.create_table('price_plan',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sessions_per_week', sa.Integer(), nullable=False),
    sa.Column('monthly_amount_agorot', sa.Integer(), nullable=False),
    sa.Column('registration_fee_agorot', sa.Integer(), nullable=True),
    sa.Column('active_from', sa.Date(), nullable=False),
    sa.Column('active_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('active_to IS NULL OR active_to >= active_from', name=op.f('ck_price_plan_price_plan_active_range')),
    sa.CheckConstraint('monthly_amount_agorot >= 0', name=op.f('ck_price_plan_price_plan_monthly_non_negative')),
    sa.CheckConstraint('sessions_per_week > 0', name=op.f('ck_price_plan_price_plan_sessions_per_week')),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_price_plan_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_plan'))
    )
    op.create_index('ix_price_plan_studio_id_active_from', 'price_plan', ['studio_id', 'active_from'], unique=False)
    op.create_index('ix_price_plan_studio_id_id', 'price_plan', ['studio_id', 'id'], unique=False)
    op.create_table('product',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_agorot', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('price_agorot >= 0', name=op.f('ck_product_product_price_non_negative')),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_product_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product'))
    )
    op.create_index('ix_product_studio_id_id', 'product', ['studio_id', 'id'], unique=False)
    op.create_index('ix_product_studio_id_is_active', 'product', ['studio_id', 'is_active'], unique=False)
    op.create_table('upay_ipn_record',
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('raw_query', sa.Text(), nullable=False),
    sa.Column('order_public_ref', sa.UUID(), nullable=True),
    sa.Column('transactionid', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.String(length=30), nullable=False),
    sa.Column('card_owner_name', sa.String(length=120), nullable=True),
    sa.Column('four_digits', sa.String(length=4), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('matched_payment_id', sa.UUID(), nullable=True),
    sa.Column('match_status', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("match_status IN ('auto', 'manual', 'unmatched', 'ignored')", name=op.f('ck_upay_ipn_record_upay_ipn_record_match_status')),
    sa.ForeignKeyConstraint(['matched_payment_id'], ['payment.id'], name='fk_upay_ipn_record_matched_payment_id', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_upay_ipn_record_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upay_ipn_record'))
    )
    op.create_index('ix_upay_ipn_record_studio_id_id', 'upay_ipn_record', ['studio_id', 'id'], unique=False)
    op.create_index('ix_upay_ipn_record_studio_id_match_status', 'upay_ipn_record', ['studio_id', 'match_status'], unique=False)
    op.create_index('uq_upay_ipn_record_transactionid', 'upay_ipn_record', ['transactionid'], unique=True)
    op.create_table('belt_rank',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('kyu', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.Column('secondary_color_hex', sa.String(length=7), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('order_index >= 0', name=op.f('ck_belt_rank_belt_rank_order_non_negative')),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], name=op.f('fk_belt_rank_class_id_class'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_belt_rank_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_belt_rank'))
    )
    op.create_index('ix_belt_rank_studio_id_id', 'belt_rank', ['studio_id', 'id'], unique=False)
    op.create_index('uq_belt_rank_class_name', 'belt_rank', ['class_id', 'name'], unique=True)
    op.create_index('uq_belt_rank_class_order', 'belt_rank', ['class_id', 'order_index'], unique=True)
    op.create_table('event',
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('location_text', sa.String(length=300), nullable=True),
    sa.Column('rsvp_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fee_agorot', sa.Integer(), nullable=True),
    sa.Column('requires_consent', sa.Boolean(), nullable=False),
    sa.Column('consent_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published', 'cancelled', 'completed')", name=op.f('ck_event_event_status')),
    sa.CheckConstraint("type IN ('competition', 'belt_exam', 'seminar', 'joint_training', 'trip', 'other')", name=op.f('ck_event_event_type')),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_event_event_time_range')),
    sa.CheckConstraint('fee_agorot IS NULL OR fee_agorot >= 0', name=op.f('ck_event_event_fee_non_negative')),
    sa.CheckConstraint('requires_consent = false OR consent_text IS NOT NULL', name=op.f('ck_event_event_consent_has_text')),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_event_location_id_location'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_event_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event'))
    )
    op.create_index('ix_event_studio_id_id', 'event', ['studio_id', 'id'], unique=False)
    op.create_index('ix_event_studio_id_starts_at', 'event', ['studio_id', 'starts_at'], unique=False)
    op.create_table('payer_fingerprint',
    sa.Column('payer_person_id', sa.UUID(), nullable=False),
    sa.Column('four_digits', sa.String(length=4), nullable=False),
    sa.Column('card_owner_name_normalized', sa.String(length=120), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_by_person_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by_person_id'], ['person.id'], name=op.f('fk_payer_fingerprint_confirmed_by_person_id_person'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payer_person_id'], ['person.id'], name=op.f('fk_payer_fingerprint_payer_person_id_person'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_payer_fingerprint_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payer_fingerprint'))
    )
    op.create_index('ix_payer_fingerprint_studio_id_id', 'payer_fingerprint', ['studio_id', 'id'], unique=False)
    op.create_index('uq_payer_fingerprint_identity', 'payer_fingerprint', ['studio_id', 'four_digits', 'card_owner_name_normalized'], unique=True)
    op.create_table('payment_order',
    sa.Column('payer_person_id', sa.UUID(), nullable=False),
    sa.Column('public_ref', sa.UUID(), nullable=False),
    sa.Column('expected_amount_agorot', sa.Integer(), nullable=False),
    sa.Column('max_payments', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_payment_ref', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'paid', 'failed', 'amount_mismatch', 'expired')", name=op.f('ck_payment_order_payment_order_status')),
    sa.CheckConstraint('expected_amount_agorot > 0', name=op.f('ck_payment_order_payment_order_amount_positive')),
    sa.CheckConstraint('max_payments BETWEEN 1 AND 12', name=op.f('ck_payment_order_payment_order_max_payments')),
    sa.ForeignKeyConstraint(['payer_person_id'], ['person.id'], name=op.f('fk_payment_order_payer_person_id_person'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_payment_order_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_order'))
    )
    op.create_index('ix_payment_order_status_created_at', 'payment_order', ['status', 'created_at'], unique=False)
    op.create_index('ix_payment_order_studio_id_id', 'payment_order', ['studio_id', 'id'], unique=False)
    op.create_index('uq_payment_order_public_ref', 'payment_order', ['public_ref'], unique=True)
    op.create_table('recurring_subscription',
    sa.Column('payer_person_id', sa.UUID(), nullable=False),
    sa.Column('amount_agorot', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'cancelled')", name=op.f('ck_recurring_subscription_recurring_subscription_status')),
    sa.CheckConstraint('amount_agorot > 0', name=op.f('ck_recurring_subscription_amount_positive')),
    sa.ForeignKeyConstraint(['payer_person_id'], ['person.id'], name=op.f('fk_recurring_subscription_payer_person_id_person'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_recurring_subscription_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recurring_subscription'))
    )
    op.create_index('ix_recurring_subscription_studio_id_id', 'recurring_subscription', ['studio_id', 'id'], unique=False)
    op.create_index('uq_recurring_subscription_active_payer', 'recurring_subscription', ['studio_id', 'payer_person_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('event_target',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=10), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("target_type = 'studio' OR target_id IS NOT NULL", name=op.f('ck_event_target_event_target_has_an_id')),
    sa.CheckConstraint("target_type IN ('studio', 'class', 'group', 'student')", name=op.f('ck_event_target_event_target_type')),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_event_target_event_id_event'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_event_target_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_target'))
    )
    op.create_index('ix_event_target_studio_id_id', 'event_target', ['studio_id', 'id'], unique=False)
    op.create_index('uq_event_target', 'event_target', ['event_id', 'target_type', 'target_id'], unique=True)
    op.create_table('payment',
    sa.Column('payer_person_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('amount_agorot', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by_person_id', sa.UUID(), nullable=True),
    sa.Column('payment_order_id', sa.UUID(), nullable=True),
    sa.Column('upay_ipn_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('external_receipt_number', sa.String(length=60), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversal_reason', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("method IN ('upay_card', 'standing_order', 'bank_transfer', 'cash', 'credit_adjustment')", name=op.f('ck_payment_payment_method')),
    sa.CheckConstraint('reversed_at IS NULL OR reversal_reason IS NOT NULL', name=op.f('ck_payment_payment_reversal_has_a_reason')),
    sa.ForeignKeyConstraint(['payer_person_id'], ['person.id'], name=op.f('fk_payment_payer_person_id_person'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_order_id'], ['payment_order.id'], name=op.f('fk_payment_payment_order_id_payment_order'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by_person_id'], ['person.id'], name=op.f('fk_payment_recorded_by_person_id_person'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_payment_studio_id_studio'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['upay_ipn_id'], ['upay_ipn_record.id'], name=op.f('fk_payment_upay_ipn_id_upay_ipn_record'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment'))
    )
    op.create_index('ix_payment_studio_id_id', 'payment', ['studio_id', 'id'], unique=False)
    op.create_index('ix_payment_studio_id_payer_person_id', 'payment', ['studio_id', 'payer_person_id'], unique=False)
    op.create_index('ix_payment_studio_id_received_at', 'payment', ['studio_id', 'received_at'], unique=False)
    op.create_table('charge',
    sa.Column('payer_person_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=15), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=True),
    sa.Column('period_month', sa.Integer(), nullable=True),
    sa.Column('amount_agorot', sa.Integer(), nullable=False),
    sa.Column('original_amount_agorot', sa.Integer(), nullable=True),
    sa.Column('proration_note', sa.String(length=200), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_by', sa.String(length=12), nullable=False),
    sa.Column('created_by_person_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("created_by IN ('billing_run', 'manual', 'event')", name=op.f('ck_charge_charge_created_by')),
    sa.CheckConstraint("kind IN ('tuition', 'registration', 'event', 'manual')", name=op.f('ck_charge_charge_kind')),
    sa.CheckConstraint("status IN ('open', 'settled', 'void', 'written_off')", name=op.f('ck_charge_charge_status')),
    sa.CheckConstraint('period_month IS NULL OR period_month BETWEEN 1 AND 12', name=op.f('ck_charge_charge_period_month')),
    sa.ForeignKeyConstraint(['created_by_person_id'], ['person.id'], name=op.f('fk_charge_created_by_person_id_person'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payer_person_id'], ['person.id'], name=op.f('fk_charge_payer_person_id_person'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_charge_student_id_student'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_charge_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_charge'))
    )
    op.create_index('ix_charge_studio_id_due_date', 'charge', ['studio_id', 'due_date'], unique=False)
    op.create_index('ix_charge_studio_id_id', 'charge', ['studio_id', 'id'], unique=False)
    op.create_index('ix_charge_studio_id_payer_person_id_status', 'charge', ['studio_id', 'payer_person_id', 'status'], unique=False)
    op.create_index('uq_charge_student_period_kind', 'charge', ['student_id', 'period_year', 'period_month', 'kind'], unique=True, postgresql_where=sa.text('student_id IS NOT NULL AND period_year IS NOT NULL'))
    op.create_table('event_exam_result',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('belt_rank_id', sa.UUID(), nullable=False),
    sa.Column('result', sa.String(length=4), nullable=False),
    sa.Column('examiner_person_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("result IN ('pass', 'fail')", name=op.f('ck_event_exam_result_event_exam_result_result')),
    sa.ForeignKeyConstraint(['belt_rank_id'], ['belt_rank.id'], name=op.f('fk_event_exam_result_belt_rank_id_belt_rank'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_event_exam_result_event_id_event'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['examiner_person_id'], ['person.id'], name=op.f('fk_event_exam_result_examiner_person_id_person'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_event_exam_result_student_id_student'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_event_exam_result_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_exam_result'))
    )
    op.create_index('ix_event_exam_result_studio_id_id', 'event_exam_result', ['studio_id', 'id'], unique=False)
    op.create_index('uq_event_exam_result', 'event_exam_result', ['event_id', 'student_id'], unique=True)
    op.create_table('student_belt',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('belt_rank_id', sa.UUID(), nullable=False),
    sa.Column('awarded_on', sa.Date(), nullable=False),
    sa.Column('awarded_by_person_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['awarded_by_person_id'], ['person.id'], name=op.f('fk_student_belt_awarded_by_person_id_person'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['belt_rank_id'], ['belt_rank.id'], name=op.f('fk_student_belt_belt_rank_id_belt_rank'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_student_belt_event_id_event'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_student_belt_student_id_student'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_student_belt_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_belt'))
    )
    op.create_index('ix_student_belt_student_id_awarded_on', 'student_belt', ['student_id', 'awarded_on'], unique=False)
    op.create_index('ix_student_belt_studio_id_id', 'student_belt', ['studio_id', 'id'], unique=False)
    op.create_index('uq_student_belt_student_rank', 'student_belt', ['student_id', 'belt_rank_id'], unique=True)
    op.create_table('event_registration',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('rsvp', sa.String(length=10), nullable=False),
    sa.Column('responded_by_person_id', sa.UUID(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('charge_id', sa.UUID(), nullable=True),
    sa.Column('attended', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("rsvp IN ('pending', 'yes', 'no')", name=op.f('ck_event_registration_event_registration_rsvp')),
    sa.ForeignKeyConstraint(['charge_id'], ['charge.id'], name=op.f('fk_event_registration_charge_id_charge'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_event_registration_event_id_event'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responded_by_person_id'], ['person.id'], name=op.f('fk_event_registration_responded_by_person_id_person'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_event_registration_student_id_student'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_event_registration_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_registration'))
    )
    op.create_index('ix_event_registration_student_id', 'event_registration', ['student_id'], unique=False)
    op.create_index('ix_event_registration_studio_id_id', 'event_registration', ['studio_id', 'id'], unique=False)
    op.create_index('uq_event_registration', 'event_registration', ['event_id', 'student_id'], unique=True)
    op.create_table('payment_allocation',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('charge_id', sa.UUID(), nullable=False),
    sa.Column('amount_agorot', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['charge_id'], ['charge.id'], name=op.f('fk_payment_allocation_charge_id_charge'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], name=op.f('fk_payment_allocation_payment_id_payment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_payment_allocation_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_allocation'))
    )
    op.create_index('ix_payment_allocation_charge_id', 'payment_allocation', ['charge_id'], unique=False)
    op.create_index('ix_payment_allocation_studio_id_id', 'payment_allocation', ['studio_id', 'id'], unique=False)
    op.create_index('uq_payment_allocation_payment_id_charge_id', 'payment_allocation', ['payment_id', 'charge_id'], unique=True)
    op.create_table('payment_order_charge',
    sa.Column('payment_order_id', sa.UUID(), nullable=False),
    sa.Column('charge_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['charge_id'], ['charge.id'], name=op.f('fk_payment_order_charge_charge_id_charge'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_order_id'], ['payment_order.id'], name=op.f('fk_payment_order_charge_payment_order_id_payment_order'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_payment_order_charge_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_order_charge'))
    )
    op.create_index('ix_payment_order_charge_charge_id', 'payment_order_charge', ['charge_id'], unique=False)
    op.create_index('ix_payment_order_charge_studio_id_id', 'payment_order_charge', ['studio_id', 'id'], unique=False)
    op.create_index('uq_payment_order_charge', 'payment_order_charge', ['payment_order_id', 'charge_id'], unique=True)
    # --- hand-written, and the only hand-written step in this file -------------
    # W2 shipped `student.price_plan_id` and `student.current_belt_id` as free-form UUID
    # columns with no constraint, because `price_plan` and `belt_rank` are created HERE --
    # this revision is the only one that creates either table. So on any database that has
    # run 0006, EVERY non-null value in those two columns is a dangling pointer: there has
    # never been a row it could reference. `app/routers/students.py` accepts a
    # `price_plan_id` in a request body and stores it unvalidated, so a staging database
    # accumulates them exactly as this developer database did (8 of 2580 students).
    #
    # Without this, the two ALTERs below fail with ForeignKeyViolation and take the whole
    # migration down. Autogenerate cannot know about it -- it compares schema, not rows.
    #
    # NULL is the only defensible landing place, not a data-loss compromise: the discarded
    # values never denoted anything. A student with a null price is one the monthly run
    # skips, which is the state they were already in -- the run reads `price_plan`, and
    # none of these ids was in it.
    #
    # Written as NOT EXISTS rather than an unconditional UPDATE so it stays correct if a
    # later edit seeds `price_plan` or `belt_rank` earlier in this same upgrade().
    # --- hand-written: the cycle constraint op.create_table silently drops -----
    # `upay_ipn_record.matched_payment_id` carries `use_alter=True` and an explicit name,
    # and both are correct in the model -- without them SQLAlchemy drops both sides of the
    # payment/upay_ipn_record cycle from its topological sort and emits CREATE TABLEs
    # Postgres rejects. But `use_alter` is honoured by `metadata.create_all()`, which
    # emits the constraint afterwards as a separate AddConstraint; `op.create_table`
    # issues only CreateTable, whose compiler SKIPS use_alter constraints and never emits
    # the follow-up. So the inline ForeignKeyConstraint above is inert: the table is
    # created without it and the reconciliation link never exists in the database.
    #
    # This fails silently -- the migration reports success -- and was caught only by
    # running `alembic check` against a freshly migrated database, where it showed up as
    # `Detected added foreign key (matched_payment_id)(id) on table upay_ipn_record`.
    #
    # Hand-writing it here is the OPPOSITE of the failure mode w4-draft.py warns about.
    # That warning is against hand-writing a constraint the MODEL does not carry, which
    # gives a database the models do not describe. Here the model carries it and the
    # generated migration does not, so this ALTER is what makes the two agree.
    op.create_foreign_key(
        'fk_upay_ipn_record_matched_payment_id',
        'upay_ipn_record',
        'payment',
        ['matched_payment_id'],
        ['id'],
        ondelete='SET NULL',
    )

    op.execute(
        """
        UPDATE student SET price_plan_id = NULL
         WHERE price_plan_id IS NOT NULL
           AND NOT EXISTS (SELECT 1 FROM price_plan p WHERE p.id = student.price_plan_id)
        """
    )
    op.execute(
        """
        UPDATE student SET current_belt_id = NULL
         WHERE current_belt_id IS NOT NULL
           AND NOT EXISTS (SELECT 1 FROM belt_rank b WHERE b.id = student.current_belt_id)
        """
    )
    op.create_foreign_key(op.f('fk_student_price_plan_id_price_plan'), 'student', 'price_plan', ['price_plan_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_student_current_belt_id_belt_rank'), 'student', 'belt_rank', ['current_belt_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # The cycle constraint added by ALTER in upgrade(). It must be dropped BEFORE the two
    # tables it links, and Alembic could not have written this itself -- it never wrote
    # the matching create.
    op.drop_constraint('fk_upay_ipn_record_matched_payment_id', 'upay_ipn_record', type_='foreignkey')
    op.drop_constraint(op.f('fk_student_current_belt_id_belt_rank'), 'student', type_='foreignkey')
    op.drop_constraint(op.f('fk_student_price_plan_id_price_plan'), 'student', type_='foreignkey')
    op.drop_index('uq_payment_order_charge', table_name='payment_order_charge')
    op.drop_index('ix_payment_order_charge_studio_id_id', table_name='payment_order_charge')
    op.drop_index('ix_payment_order_charge_charge_id', table_name='payment_order_charge')
    op.drop_table('payment_order_charge')
    op.drop_index('uq_payment_allocation_payment_id_charge_id', table_name='payment_allocation')
    op.drop_index('ix_payment_allocation_studio_id_id', table_name='payment_allocation')
    op.drop_index('ix_payment_allocation_charge_id', table_name='payment_allocation')
    op.drop_table('payment_allocation')
    op.drop_index('uq_event_registration', table_name='event_registration')
    op.drop_index('ix_event_registration_studio_id_id', table_name='event_registration')
    op.drop_index('ix_event_registration_student_id', table_name='event_registration')
    op.drop_table('event_registration')
    op.drop_index('uq_student_belt_student_rank', table_name='student_belt')
    op.drop_index('ix_student_belt_studio_id_id', table_name='student_belt')
    op.drop_index('ix_student_belt_student_id_awarded_on', table_name='student_belt')
    op.drop_table('student_belt')
    op.drop_index('uq_event_exam_result', table_name='event_exam_result')
    op.drop_index('ix_event_exam_result_studio_id_id', table_name='event_exam_result')
    op.drop_table('event_exam_result')
    op.drop_index('uq_charge_student_period_kind', table_name='charge', postgresql_where=sa.text('student_id IS NOT NULL AND period_year IS NOT NULL'))
    op.drop_index('ix_charge_studio_id_payer_person_id_status', table_name='charge')
    op.drop_index('ix_charge_studio_id_id', table_name='charge')
    op.drop_index('ix_charge_studio_id_due_date', table_name='charge')
    op.drop_table('charge')
    op.drop_index('ix_payment_studio_id_received_at', table_name='payment')
    op.drop_index('ix_payment_studio_id_payer_person_id', table_name='payment')
    op.drop_index('ix_payment_studio_id_id', table_name='payment')
    op.drop_table('payment')
    op.drop_index('uq_event_target', table_name='event_target')
    op.drop_index('ix_event_target_studio_id_id', table_name='event_target')
    op.drop_table('event_target')
    op.drop_index('uq_recurring_subscription_active_payer', table_name='recurring_subscription', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_recurring_subscription_studio_id_id', table_name='recurring_subscription')
    op.drop_table('recurring_subscription')
    op.drop_index('uq_payment_order_public_ref', table_name='payment_order')
    op.drop_index('ix_payment_order_studio_id_id', table_name='payment_order')
    op.drop_index('ix_payment_order_status_created_at', table_name='payment_order')
    op.drop_table('payment_order')
    op.drop_index('uq_payer_fingerprint_identity', table_name='payer_fingerprint')
    op.drop_index('ix_payer_fingerprint_studio_id_id', table_name='payer_fingerprint')
    op.drop_table('payer_fingerprint')
    op.drop_index('ix_event_studio_id_starts_at', table_name='event')
    op.drop_index('ix_event_studio_id_id', table_name='event')
    op.drop_table('event')
    op.drop_index('uq_belt_rank_class_order', table_name='belt_rank')
    op.drop_index('uq_belt_rank_class_name', table_name='belt_rank')
    op.drop_index('ix_belt_rank_studio_id_id', table_name='belt_rank')
    op.drop_table('belt_rank')
    op.drop_index('uq_upay_ipn_record_transactionid', table_name='upay_ipn_record')
    op.drop_index('ix_upay_ipn_record_studio_id_match_status', table_name='upay_ipn_record')
    op.drop_index('ix_upay_ipn_record_studio_id_id', table_name='upay_ipn_record')
    op.drop_table('upay_ipn_record')
    op.drop_index('ix_product_studio_id_is_active', table_name='product')
    op.drop_index('ix_product_studio_id_id', table_name='product')
    op.drop_table('product')
    op.drop_index('ix_price_plan_studio_id_id', table_name='price_plan')
    op.drop_index('ix_price_plan_studio_id_active_from', table_name='price_plan')
    op.drop_table('price_plan')
    op.drop_index('uq_billing_run_studio_period', table_name='billing_run')
    op.drop_index('ix_billing_run_studio_id_id', table_name='billing_run')
    op.drop_table('billing_run')
    # ### end Alembic commands ###
