"""w5 comms and reports (M8 || M9)

SPEC 5.11's notification fan-out, 5.12's calendar feeds and 11.3's export request: six
tables from two model files promoted out of app/models/_pending/ in W5's contract commit,
authored on main before either worktree exists -- a lane never runs `alembic revision`. The
last of the four wave revisions, and it closes the set: 0006-0009 cover every model the M0
contract branch could author but not migrate.

**The scope cut is enforced in the schema, not only in the UI.** There is no `reply_to_id`,
no `thread_id` and no `sender_person_id` on any of these six tables, and none may be added.
SPEC 2.3 puts in-app two-way chat out of scope, 5.11 permits exactly two levels -- a push
notification and a ONE-WAY inbox -- and D9.1 cut `שיחה עם המשרד` from parent artboard `2b`.
`tests/contracts/test_w5_models.py` asserts their absence by name, because a migration that
quietly adds one is how a scope decision gets reversed a year later without anyone making it.

**`notification_delivery.status` carries six values and collapsing any of them breaks the
report they exist for:** queued, sent, delivered, failed, `no_token`, `denied`. Push is
opt-in on iOS and Android 13+ (SPEC 12), so "never installed the app" and "turned
notifications off" are different conversations to have with a parent, and neither of them is
"the send errored". Folding them into `failed` turns the manager's list into a count nobody
can act on -- and 5.11 permits no email or SMS fallback, so that list is the only remaining
route to a parent who is not reading the inbox.

**Both token columns are unique PRODUCT-WIDE, not per studio.** A push registration
identifies a device, and 5.12's feed lives at an unauthenticated URL carrying no studio to
disambiguate it, so a per-tenant constraint would let two studios issue the same
subscription URL. `uq_push_token_token` and `uq_calendar_feed_token` are plain unique
indexes on `token` alone -- the one place in this revision where the leading-`studio_id`
habit is deliberately not followed.

**The unread index is partial.** `ix_notification_studio_id_person_id_unread` carries
`postgresql_where=read_at IS NULL`. It serves 5.11's inbox badge, and within a month of use
the read rows are the overwhelming majority; an unconditional index would grow without bound
to answer a question only ever asked about the small end of it.

**Three paired CHECKs, each one a state the UI would otherwise render as a lie.**
`announcement`: `(scope_type = 'studio') = (scope_id IS NULL)`. `data_export_request`:
`(status = 'completed') = (object_key IS NOT NULL)`, plus the matching `completed_at`
pairing. A completed export with no `object_key` is a download link to nothing, shown to a
guardian who has just been told their data is ready. All three read as redundant to a
tidy-up and are the likeliest thing in here for one to drop. They are not redundant.

**`data_export_request.object_key` is a String pointer and never the bundle.** SPEC 8.1 puts
export bundles in object storage. Inlining one would put a child's complete record -- health
declarations included -- into every backup, every replica and every `pg_dump`.

**`notification_delivery` and `push_token` carry `studio_id` even though 4.3's shorthand
column list for them does not.** Both are children of tenant-scoped rows and `TenantSession`
filters on the mixin, so a child without `studio_id` is a row the tenant filter cannot see.
Neither has a reason to be global, so neither belongs in `CROSS_TENANT_TABLES`.

Verified on a fresh database and on a 0008 one; `notification_delivery` references
`notification` and both reference `person` from 0005, so table ordering only bites on the
fresh run.

Revision ID: 0009
Revises: 0008
Create Date: 2026-08-26 17:20:20.827652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0009'
down_revision: Union[str, Sequence[str], None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement',
    sa.Column('author_person_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('scope_type', sa.String(length=10), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("(scope_type = 'studio') = (scope_id IS NULL)", name=op.f('ck_announcement_announcement_scope_id_present')),
    sa.CheckConstraint("scope_type IN ('studio', 'class', 'group')", name=op.f('ck_announcement_announcement_scope_type')),
    sa.ForeignKeyConstraint(['author_person_id'], ['person.id'], name=op.f('fk_announcement_author_person_id_person'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_announcement_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcement'))
    )
    op.create_index('ix_announcement_studio_id_id', 'announcement', ['studio_id', 'id'], unique=False)
    op.create_index('ix_announcement_studio_id_published_at', 'announcement', ['studio_id', 'published_at'], unique=False)
    op.create_index('ix_announcement_studio_id_scheduled_for', 'announcement', ['studio_id', 'scheduled_for'], unique=False)
    op.create_table('calendar_feed',
    sa.Column('subject_type', sa.String(length=8), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("subject_type IN ('guardian', 'coach')", name=op.f('ck_calendar_feed_calendar_feed_subject_type')),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_calendar_feed_person_id_person'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_calendar_feed_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_feed'))
    )
    op.create_index('ix_calendar_feed_studio_id_id', 'calendar_feed', ['studio_id', 'id'], unique=False)
    op.create_index('uq_calendar_feed_person_id_subject_type', 'calendar_feed', ['person_id', 'subject_type'], unique=True)
    op.create_index('uq_calendar_feed_token', 'calendar_feed', ['token'], unique=True)
    op.create_table('data_export_request',
    sa.Column('subject_person_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_person_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=9), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("(status = 'completed') = (object_key IS NOT NULL)", name=op.f('ck_data_export_request_data_export_request_key_when_completed')),
    sa.CheckConstraint("(status IN ('completed', 'failed', 'expired')) = (completed_at IS NOT NULL)", name=op.f('ck_data_export_request_data_export_request_finished_at')),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed', 'expired')", name=op.f('ck_data_export_request_data_export_request_status')),
    sa.ForeignKeyConstraint(['requested_by_person_id'], ['person.id'], name=op.f('fk_data_export_request_requested_by_person_id_person'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_data_export_request_studio_id_studio'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_person_id'], ['person.id'], name=op.f('fk_data_export_request_subject_person_id_person'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_export_request'))
    )
    op.create_index('ix_data_export_request_studio_id_id', 'data_export_request', ['studio_id', 'id'], unique=False)
    op.create_index('ix_data_export_request_studio_id_status', 'data_export_request', ['studio_id', 'status'], unique=False)
    op.create_index('ix_data_export_request_studio_id_subject_person_id', 'data_export_request', ['studio_id', 'subject_person_id'], unique=False)
    op.create_table('notification',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_notification_person_id_person'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_notification_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    op.create_index('ix_notification_studio_id_id', 'notification', ['studio_id', 'id'], unique=False)
    op.create_index('ix_notification_studio_id_person_id_created_at', 'notification', ['studio_id', 'person_id', 'created_at'], unique=False)
    op.create_index('ix_notification_studio_id_person_id_unread', 'notification', ['studio_id', 'person_id'], unique=False, postgresql_where=sa.text('read_at IS NULL'))
    op.create_table('push_token',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('app', sa.String(length=6), nullable=False),
    sa.Column('platform', sa.String(length=7), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("app IN ('staff', 'parent')", name=op.f('ck_push_token_push_token_app')),
    sa.CheckConstraint("platform IN ('ios', 'android', 'web')", name=op.f('ck_push_token_push_token_platform')),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_push_token_person_id_person'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_push_token_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_token'))
    )
    op.create_index('ix_push_token_studio_id_id', 'push_token', ['studio_id', 'id'], unique=False)
    op.create_index('ix_push_token_studio_id_person_id_app', 'push_token', ['studio_id', 'person_id', 'app'], unique=False)
    op.create_index('uq_push_token_token', 'push_token', ['token'], unique=True)
    op.create_table('notification_delivery',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=6), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("channel IN ('push', 'inapp')", name=op.f('ck_notification_delivery_notification_delivery_channel')),
    sa.CheckConstraint("status IN ('queued', 'sent', 'delivered', 'failed', 'no_token', 'denied')", name=op.f('ck_notification_delivery_notification_delivery_status')),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], name=op.f('fk_notification_delivery_notification_id_notification'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_notification_delivery_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_delivery'))
    )
    op.create_index('ix_notification_delivery_studio_id_id', 'notification_delivery', ['studio_id', 'id'], unique=False)
    op.create_index('ix_notification_delivery_studio_id_status', 'notification_delivery', ['studio_id', 'status'], unique=False)
    op.create_index('uq_notification_delivery_notification_id_channel', 'notification_delivery', ['notification_id', 'channel'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_notification_delivery_notification_id_channel', table_name='notification_delivery')
    op.drop_index('ix_notification_delivery_studio_id_status', table_name='notification_delivery')
    op.drop_index('ix_notification_delivery_studio_id_id', table_name='notification_delivery')
    op.drop_table('notification_delivery')
    op.drop_index('uq_push_token_token', table_name='push_token')
    op.drop_index('ix_push_token_studio_id_person_id_app', table_name='push_token')
    op.drop_index('ix_push_token_studio_id_id', table_name='push_token')
    op.drop_table('push_token')
    op.drop_index('ix_notification_studio_id_person_id_unread', table_name='notification', postgresql_where=sa.text('read_at IS NULL'))
    op.drop_index('ix_notification_studio_id_person_id_created_at', table_name='notification')
    op.drop_index('ix_notification_studio_id_id', table_name='notification')
    op.drop_table('notification')
    op.drop_index('ix_data_export_request_studio_id_subject_person_id', table_name='data_export_request')
    op.drop_index('ix_data_export_request_studio_id_status', table_name='data_export_request')
    op.drop_index('ix_data_export_request_studio_id_id', table_name='data_export_request')
    op.drop_table('data_export_request')
    op.drop_index('uq_calendar_feed_token', table_name='calendar_feed')
    op.drop_index('uq_calendar_feed_person_id_subject_type', table_name='calendar_feed')
    op.drop_index('ix_calendar_feed_studio_id_id', table_name='calendar_feed')
    op.drop_table('calendar_feed')
    op.drop_index('ix_announcement_studio_id_scheduled_for', table_name='announcement')
    op.drop_index('ix_announcement_studio_id_published_at', table_name='announcement')
    op.drop_index('ix_announcement_studio_id_id', table_name='announcement')
    op.drop_table('announcement')
    # ### end Alembic commands ###
