"""notification preference (M8)

SPEC 5.11's second sentence, which 4.3 has no table for: "Every notification type is
individually mutable per user, except health-declaration and payment-failure notices, which
are transactional." W5's contract commit promoted six tables and this was not among them,
because 4.3's column shorthand never listed it.

**Authored inside lane COMMS rather than in the wave's contract commit, and that is an
exception rather than a precedent.** CLAUDE.md is explicit that a lane never runs
`alembic revision`; the alternative here was a settings screen that could read a preference
and not write one, which is a switch that lies to the person holding it. Agreed before any
code was written and recorded in docs/superpowers/plans/2026-08-26-m8-comms.md under
"Approved exceptions". The next wave's contract commit is where a table belongs again.

**Absence means on, and the table is empty until somebody changes something.** No defaults
are seeded here and none should be. A new guardian receives everything without eight inserts
at sign-up, and a preference group added in a later milestone defaults to ON for people who
never saw the screen -- rather than being silently off for every existing user because
nobody remembered to backfill them. That is why there is no INSERT in this revision, and why
`enabled` carries a model-level default rather than a server default: a server default would
only ever apply to a row somebody deliberately created.

**Two switches this table cannot turn off, and neither is expressed here.** 5.11's
transactional exemption is a rule about DELIVERY, not about storage: `health` refuses to be
disabled at all, and `billing.payment_failed` still sends inside a disabled `payment` group.
Both live in app/services/comms/kinds.py, where the fan-out reads them. Encoding them as a
constraint would mean a migration every time the trigger table grows -- which is every
milestone -- and 4.3 already made that argument for `notification.kind` being a plain string.

**`kind_group`, not `kind`.** 5.11's trigger table has fifteen rows and the settings screen
offers eight switches. A row per kind would make "turn off payment reminders" a five-row
write that can half-succeed, leaving a parent muted for the day-3 reminder and not the
day-7.

`ck_notification_preference_notification_preference_kind_group` is 61 characters. Counted,
because 0009 shipped a 64-character constraint name that PostgreSQL truncated at 63 while
the migration wrote the full one, so the two disagreed forever and `alembic check` reported
drift on a schema nobody had touched. Every identifier here is under the limit; that one is
the longest.

Verified on a 0009 database. Nothing here references a table 0009 did not already create, so
ordering does not bite on a fresh run either.

Revision ID: 0010
Revises: 0009
Create Date: 2026-08-26 18:54:22.467327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0010'
down_revision: Union[str, Sequence[str], None] = '0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preference',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('kind_group', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("kind_group IN ('session_cancelled', 'coach_substituted', 'announcement', 'event', 'payment', 'belt', 'attendance', 'health')", name=op.f('ck_notification_preference_notification_preference_kind_group')),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_notification_preference_person_id_person'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_notification_preference_studio_id_studio'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_preference'))
    )
    op.create_index('ix_notification_preference_studio_id_id', 'notification_preference', ['studio_id', 'id'], unique=False)
    op.create_index('uq_notification_preference_person_id_kind_group', 'notification_preference', ['person_id', 'kind_group'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_notification_preference_person_id_kind_group', table_name='notification_preference')
    op.drop_index('ix_notification_preference_studio_id_id', table_name='notification_preference')
    op.drop_table('notification_preference')
    # ### end Alembic commands ###
