"""coach unavailability, a note's kind, and the end of coach-substituted

Revision ID: 0023
Revises: 0022

One revision carrying the staff app redesign's three schema changes (checkpoint 5 of
docs/superpowers/specs/2026-09-06-staff-app-redesign.md, §6.1/§6.2/§6.4), because `main`
owns `alembic/versions/**` and a wave gets one revision -- two later checkpoints (session
briefings, the unavailability screen) both need a piece of this and neither owns a
migration of its own.

**1. `coach_constraint`** (§6.1). A coach files a reason -- reserve duty, illness, a
competition -- as a CODE the client renders, over a time window rather than a date range,
because the schedule underneath it is in times. `all_day` stays its own column: a request
that genuinely runs midnight-to-midnight and one that is flagged "all day" round-trip to
the same two timestamps, and without the flag the two cannot be told apart on the way back
out. `status` starts `pending`; a manager's approve/refuse and the filer's own withdrawal
are all status transitions, never a row deletion, because the manager's queue and the
coach's own history both read this table afterwards.

**2. `session_note.kind`** (§6.2, decision 16). One column, `plan | summary`, not null,
default `summary` -- which is what every existing row already is. **Backfilled explicitly**
with an UPDATE rather than left to the default alone: the column is added nullable, every
existing NULL is set to `summary`, and only then is it made NOT NULL. Relying on the
default to paper over old rows would mean the column's own default value was doing
double duty as a claim about history it never made.

**3. Removing `coach_substituted`** (§6.4, decision 13) -- the only irreversible step
here, and the reason this migration is reviewed by hand rather than autogenerated.
`_set_staff` in `app/services/schedule/service.py` has never notified anyone when a
session's coach changes, so nothing has ever sent a notification under this kind -- but
the settings screen has rendered the switch since it shipped, and toggling it writes an
ordinary row. Those rows exist on live data and violate a CHECK constraint narrowed to
seven groups, so **the DELETE runs before the constraint is dropped and recreated** --
recreating it first would reject the very rows this step has to remove. `PREFERENCE_GROUPS`
(app/models/comms.py) and `_GROUP_BY_PREFIX` (app/services/comms/kinds.py) lose the group
and its mapping in the same commit as this revision, so the three stay in lock-step rather
than drifting.

Verified against the dev database (2026-09-06/07): 99 `notification_preference` rows exist,
of which exactly 6 carry `kind_group = 'coach_substituted'` -- the number the DELETE below
removes.

**The downgrade is real but partial, and says so.** The table and the column both drop
cleanly. The CHECK constraint goes back to naming all eight groups, so the schema is
genuinely reversible. **The deleted `notification_preference` rows do not come back** --
there is no record of who had `coach_substituted` set to what, and no comment in this file
pretends otherwise.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0023"
down_revision: str | Sequence[str] | None = "0022"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: The name SQLAlchemy's naming convention (app/models/base.py) computes for
#: `NotificationPreference`'s CHECK constraint -- `ck_%(table_name)s_%(constraint_name)s`
#: with the model's own `name="notification_preference_kind_group"`. Counted at 61
#: characters in revision 0010's own docstring, because 0009 once shipped a 64-character
#: name Postgres truncated at 63 while the migration wrote the full one -- this one is
#: reused verbatim on both sides of the drop/recreate so it never has that problem.
_NOTIFICATION_PREFERENCE_KIND_GROUP_CHECK = (
    "ck_notification_preference_notification_preference_kind_group"
)


def upgrade() -> None:
    # -- 1. §6.1 -- coach unavailability -------------------------------------------------
    op.create_table(
        "coach_constraint",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        # TenantMixin's column, written out because a migration cannot inherit the mixin.
        sa.Column("studio_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("person_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("all_day", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("substitute_person_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("decided_by_person_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "reason IN ('reserve_duty', 'competition', 'studies', 'illness', 'vacation', "
            "'family', 'other')",
            name=op.f("ck_coach_constraint_coach_constraint_reason"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'refused', 'withdrawn')",
            name=op.f("ck_coach_constraint_coach_constraint_status"),
        ),
        sa.CheckConstraint(
            "ends_at > starts_at", name=op.f("ck_coach_constraint_coach_constraint_time_range")
        ),
        # RESTRICT, matching TenantMixin: a studio row is never deleted out from under the
        # rows that belong to it.
        sa.ForeignKeyConstraint(
            ["studio_id"],
            ["studio.id"],
            name=op.f("fk_coach_constraint_studio_id_studio"),
            ondelete="RESTRICT",
        ),
        # RESTRICT: the coach who filed it is evidence, same reasoning as session_staff.
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.id"],
            name=op.f("fk_coach_constraint_person_id_person"),
            ondelete="RESTRICT",
        ),
        # SET NULL: a suggestion, not a decision -- see the model docstring.
        sa.ForeignKeyConstraint(
            ["substitute_person_id"],
            ["person.id"],
            name=op.f("fk_coach_constraint_substitute_person_id_person"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_person_id"],
            ["person.id"],
            name=op.f("fk_coach_constraint_decided_by_person_id_person"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coach_constraint")),
    )
    # G9's leading composite index, the one TenantMixin adds to every tenant table.
    op.create_index("ix_coach_constraint_studio_id_id", "coach_constraint", ["studio_id", "id"])
    # A coach's own -- GET /coach-constraints?mine=true.
    op.create_index(
        "ix_coach_constraint_studio_id_person_id",
        "coach_constraint",
        ["studio_id", "person_id"],
    )
    # The pending queue behind the manager's alert -- GET /coach-constraints?status=pending.
    op.create_index(
        "ix_coach_constraint_studio_id_status", "coach_constraint", ["studio_id", "status"]
    )

    # -- 2. §6.2 -- session_note.kind, backfilled explicitly ----------------------------
    op.add_column("session_note", sa.Column("kind", sa.String(length=10), nullable=True))
    op.execute("UPDATE session_note SET kind = 'summary' WHERE kind IS NULL")
    op.alter_column("session_note", "kind", nullable=False)
    op.create_check_constraint(
        op.f("ck_session_note_session_note_kind"), "session_note", "kind IN ('plan', 'summary')"
    )

    # -- 3. §6.4 -- the coach-substituted switch, in the order that does not fail on live
    # data: the rows first, then the constraint that would otherwise reject them.
    op.execute("DELETE FROM notification_preference WHERE kind_group = 'coach_substituted'")
    op.drop_constraint(
        op.f(_NOTIFICATION_PREFERENCE_KIND_GROUP_CHECK),
        "notification_preference",
        type_="check",
    )
    op.create_check_constraint(
        op.f(_NOTIFICATION_PREFERENCE_KIND_GROUP_CHECK),
        "notification_preference",
        "kind_group IN ('session_cancelled', 'announcement', 'event', 'payment', 'belt', "
        "'attendance', 'health')",
    )


def downgrade() -> None:
    # -- 3. §6.4, reversed. The CHECK accepts all eight groups again, which makes the
    # SCHEMA reversible. The DELETE above is not: every row that had named
    # 'coach_substituted' is gone, and nothing here restores who had switched it on or off.
    op.drop_constraint(
        op.f(_NOTIFICATION_PREFERENCE_KIND_GROUP_CHECK),
        "notification_preference",
        type_="check",
    )
    op.create_check_constraint(
        op.f(_NOTIFICATION_PREFERENCE_KIND_GROUP_CHECK),
        "notification_preference",
        "kind_group IN ('session_cancelled', 'coach_substituted', 'announcement', 'event', "
        "'payment', 'belt', 'attendance', 'health')",
    )

    # -- 2. §6.2, reversed.
    op.drop_constraint("ck_session_note_session_note_kind", "session_note", type_="check")
    op.drop_column("session_note", "kind")

    # -- 1. §6.1, reversed.
    op.drop_index("ix_coach_constraint_studio_id_status", table_name="coach_constraint")
    op.drop_index("ix_coach_constraint_studio_id_person_id", table_name="coach_constraint")
    op.drop_index("ix_coach_constraint_studio_id_id", table_name="coach_constraint")
    op.drop_table("coach_constraint")
