"""ops: job heartbeats and ops events

Two GLOBAL tables -- neither inherits TenantMixin, and
tests/invariants/test_02_tenant_tables_are_scoped.py carries the reason for each rather
than letting them pass by omission.

`job_run` is the heartbeat: one row per execution of one scheduled job, written by
app/core/jobs.py. It exists because four workers were scheduled nowhere for a whole
milestone and nothing noticed -- and nothing could have, because a job that never runs
raises nothing for an error hook to catch. The index leads with `job_name` because the
only read in the hot path is "the newest successful run of this job".

`ops_event` is what nothing else writes down: unhandled API exceptions, and the record of
an alert having been sent so the same red does not mail every fifteen minutes. The
business signals are deliberately NOT here -- they are derived from `billing_run` and
`upay_ipn_record`, because a signal computed from the real table cannot drift from it.

Neither table may carry a person: no message text, no populated route, no studio id. See
app/models/ops.py.

Revision ID: 00cc140ce237
Revises: 0014
Create Date: 2026-08-30 01:03:44.010178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00cc140ce237'
down_revision: Union[str, Sequence[str], None] = '0014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_run',
    sa.Column('job_name', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_type', sa.String(length=128), nullable=True),
    sa.Column('error_where', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_run'))
    )
    op.create_index('ix_job_run_job_name_started_at', 'job_run', ['job_name', 'started_at'], unique=False)
    op.create_table('ops_event',
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ops_event'))
    )
    op.create_index('ix_ops_event_kind_at', 'ops_event', ['kind', 'at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ops_event_kind_at', table_name='ops_event')
    op.drop_table('ops_event')
    op.drop_index('ix_job_run_job_name_started_at', table_name='job_run')
    op.drop_table('job_run')
    # ### end Alembic commands ###
