"""add DeletionRequest model for privacy lane

Revision ID: b943f8b4b4ee
Revises: 0010
Create Date: 2026-08-26 23:02:58.584145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b943f8b4b4ee'
down_revision: Union[str, Sequence[str], None] = '0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deletion_request',
    sa.Column('subject_person_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_person_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=9), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("(status = 'failed') = (error IS NOT NULL)", name=op.f('ck_deletion_request_deletion_request_error_when_failed')),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed')", name=op.f('ck_deletion_request_deletion_request_status')),
    sa.ForeignKeyConstraint(['requested_by_person_id'], ['person.id'], name=op.f('fk_deletion_request_requested_by_person_id_person'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], name=op.f('fk_deletion_request_studio_id_studio'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_person_id'], ['person.id'], name=op.f('fk_deletion_request_subject_person_id_person'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deletion_request'))
    )
    op.create_index('ix_deletion_request_studio_id_id', 'deletion_request', ['studio_id', 'id'], unique=False)
    op.create_index('ix_deletion_request_studio_id_status', 'deletion_request', ['studio_id', 'status'], unique=False)
    op.create_index('ix_deletion_request_studio_id_subject_person_id', 'deletion_request', ['studio_id', 'subject_person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deletion_request_studio_id_subject_person_id', table_name='deletion_request')
    op.drop_index('ix_deletion_request_studio_id_status', table_name='deletion_request')
    op.drop_index('ix_deletion_request_studio_id_id', table_name='deletion_request')
    op.drop_table('deletion_request')
    # ### end Alembic commands ###
