// Where a tapped notification lands, per app — and the Vite plugin that ships the handler.
//
// **Why the handler is bolted on instead of written into the worker.** vite-plugin-pwa has
// two strategies. `injectManifest` would let us author the whole service worker in
// TypeScript, but it hands us the precache wiring too — and this repo's offline behaviour
// (§6.1's font priming, `navigateFallback`, `cleanupOutdatedCaches`) is already correct,
// already asserted by each app's `sw-precache.test.ts`, and is the one thing a coach in a
// basement depends on. `generateSW` plus `workbox.importScripts` adds the push half without
// touching any of it, and needs no `workbox-*` runtime package that is not already installed.
//
// **The cache-busting works by accident of the glob, and that is worth knowing.** The
// generated `sw.js` contains the constant string `importScripts("push-sw.js")`, so a change
// to the handler alone would not change `sw.js` and no browser would ever pick it up. It
// does change, because `push-sw.js` matches each app's `globPatterns` (`**/*.js`) and so
// appears in the precache manifest INSIDE `sw.js` with a content revision. Drop `.js` from
// a globPattern and push handlers stop updating, silently, on every device already running.
//
// **The Hebrew below cannot live in packages/i18n.** The handler is served verbatim and
// evaluated in the service worker's global scope — it is not bundled, so it can import
// nothing — and a worker woken by a push has no session and therefore no locale to pick a
// language with. It is moot in practice: every title and body comes from the server already
// written in Hebrew (`app/services/comms/reminders.py` and friends), so the whole
// notification pipeline is Hebrew-only today. These two strings only ever appear if a push
// arrives carrying no data at all, which our own sender never sends.

import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))

/** @typedef {{ routes: Record<string, string>, fallback: string }} PushRouting */

/**
 * Kind prefix → hash route, per app.
 *
 * **Keyed on the prefix**, the same convention `app/services/comms/kinds.py` uses to decide
 * which preference switch governs a kind. One convention in both places, so `attendance.at_risk`
 * and `attendance.absence_reported` need no entry each.
 *
 * `:student_id` and friends are filled from the notification's payload. A prefix with no
 * entry, or an entry whose payload field is missing, falls back — see `routeFor` in
 * push-sw-source.js for why a dead deep link is worse than the inbox.
 *
 * **Only routes that exist.** Every value here was read off the app's own hash router
 * (`apps/<app>/src/App.tsx`), not guessed: a route that does not match lands the parent on
 * the app's unknown-hash home, which looks exactly like the notification having done nothing.
 *
 * @type {Record<string, PushRouting>}
 */
export const PUSH_ROUTING = {
  parent: {
    routes: {
      // The composite child card — where a belt award and an absence both actually live.
      belt: '#/student/:student_id',
      attendance: '#/student/:student_id',
      billing: '#/payments',
      event: '#/events',
      announcement: '#/announcements',
      // Home: the health gate and the day's schedule are both on it, and neither has a
      // hash route of its own to send someone to.
      health: '#/',
      session: '#/',
    },
    // The inbox, because every notification in the product is also a row in it — so the
    // fallback is never a screen that fails to explain why the phone buzzed.
    fallback: '#/announcements',
  },
  staff: {
    routes: {
      session: '#/schedule',
      attendance: '#/schedule',
      event: '#/events',
      billing: '#/cash',
    },
    fallback: '#/schedule',
  },
}

/** Shown only when a push arrives with no data — see the header. */
const FALLBACK_TITLE = 'עדכון חדש'
const FALLBACK_BODY = 'יש לכם הודעה חדשה במועדון'

/** The file `workbox.importScripts` names. Root-relative to the worker's own scope. */
export const PUSH_SW_FILENAME = 'push-sw.js'

/**
 * The handler, with this app's routing table prepended.
 *
 * Exported so `__tests__/push-sw.test.ts` can evaluate exactly the bytes the browser gets,
 * rather than a hand-built approximation of them.
 *
 * @param {keyof typeof PUSH_ROUTING} app
 * @returns {string}
 */
export function pushServiceWorkerSource(app) {
  const routing = PUSH_ROUTING[app]
  if (!routing) throw new Error(`No push routing declared for app "${app}"`)
  const handler = readFileSync(resolve(HERE, 'push-sw-source.js'), 'utf-8')
  const header = [
    `// Generated by tools/push-sw.mjs for the ${app} app. Do not edit — edit the tool.`,
    `self.__PUSH_ROUTES = ${JSON.stringify(routing.routes)}`,
    `self.__PUSH_FALLBACK = ${JSON.stringify(routing.fallback)}`,
    `self.__PUSH_FALLBACK_TITLE = ${JSON.stringify(FALLBACK_TITLE)}`,
    `self.__PUSH_FALLBACK_BODY = ${JSON.stringify(FALLBACK_BODY)}`,
    '',
  ].join('\n')
  return `${header}\n${handler}`
}

/**
 * Emits `push-sw.js` into the build.
 *
 * `generateBundle` rather than `writeBundle` or a `public/` file: Rollup writes emitted
 * assets before Vite's `closeBundle`, which is the hook vite-plugin-pwa globs the output
 * directory in. A `public/` copy would work too, but would put the same generated file in
 * three app directories, where the next person to edit one would not find the other two.
 *
 * @param {keyof typeof PUSH_ROUTING} app
 */
export function pushServiceWorkerPlugin(app) {
  return {
    name: 'studio:push-service-worker',
    apply: 'build',
    generateBundle() {
      this.emitFile({
        type: 'asset',
        fileName: PUSH_SW_FILENAME,
        source: pushServiceWorkerSource(app),
      })
    },
  }
}
