/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/accept-invitation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Invitation Code
         * @description §6.1 step 3 -- '[ יש לי קוד הזמנה ]'.
         *
         *     The same `accept_invitation` the callback uses, reached by someone who is already
         *     signed in. Without it, a correctly-invited parent whose email differs from the
         *     invitation by one character has no way forward at all -- and cannot tell their
         *     situation apart from a genuine refusal.
         */
        post: operations["accept_invitation_code_api_v1_auth_accept_invitation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Ends the session server-side, not merely locally.
         *
         *     Revoking the family is what makes this different from clearing a cookie: a copy of
         *     the cookie taken before logout would otherwise still refresh.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description §6.1's resolve step.
         *
         *     `access` and `studios` are re-derived from the database rather than read off the
         *     token. §3.1's "a query, not a role check" is only true if this endpoint asks -- a
         *     cached answer here is how a revoked coach keeps their app for fifteen more minutes.
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Providers
         * @description The sign-in buttons the client may render.
         *
         *     Only configured providers. §5.2 keeps Apple in scope and HB-apple-developer keeps it
         *     unconfigurable, so this is what stops an Apple button appearing on a deployment that
         *     cannot complete an Apple sign-in.
         */
        get: operations["list_providers_api_v1_auth_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description §5.2's rotation.
         *
         *     Every failure is the same 401 with no reason. `RefreshRejectedError.reason` goes to
         *     the log and nowhere else: telling a caller *why* their token failed tells an attacker
         *     whether the token existed at all.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/switch-studio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Switch Studio
         * @description §5.2 -- 'A person belonging to more than one studio gets a studio switcher.'
         *
         *     The target is checked against this identity's own memberships. A switch endpoint that
         *     trusted its input would be a cross-tenant read with a friendly name.
         */
        post: operations["switch_studio_api_v1_auth_switch_studio_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Callback
         * @description §5.2's server-side exchange, and §6.1 step 3's identity resolution.
         */
        post: operations["callback_api_v1_auth__provider__callback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/{provider}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Start
         * @description §5.2 -- 'a standard top-level redirect, then PKCE code exchange server-side.'
         *
         *     A 307 to the provider and never a rendered interstitial: an interstitial is one step
         *     closer to a webview, and Google answers `disallowed_useragent` inside one.
         */
        get: operations["start_api_v1_auth__provider__start_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Classes */
        get: operations["list_classes_api_v1_classes_get"];
        put?: never;
        /** Create Class */
        post: operations["create_class_api_v1_classes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Groups */
        get: operations["list_groups_api_v1_groups_get"];
        put?: never;
        /** Create Group */
        post: operations["create_group_api_v1_groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{group_id}/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Group Staff */
        get: operations["list_group_staff_api_v1_groups__group_id__staff_get"];
        put?: never;
        /**
         * Assign Group Staff
         * @description §5.1's wizard step 5. Creates the group_staff row AND the group-scoped role
         *     assignment -- see StructureService.assign_staff for why that is one call.
         */
        post: operations["assign_group_staff_api_v1_groups__group_id__staff_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Health
         * @description Liveness. Deliberately carries no tenant data and needs no auth.
         *
         *     `revision` is best-effort and never affects `status`: this endpoint answers "is this
         *     process alive", and a database it cannot reach does not make it dead. Letting the
         *     failure propagate would turn every database blip into a page.
         */
        get: operations["read_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Health Templates
         * @description Conflict C3's read side, so M3 can find the trial template it must present.
         *
         *     Manager and owner only: §3.2 gives 'Read full health declaration' to those two, and
         *     §6.4 puts the template editor on the manager dashboard. A coach has no business here
         *     -- they see `derived_flags` and nothing else (§5.5).
         */
        get: operations["list_health_templates_api_v1_health_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Locations */
        get: operations["list_locations_api_v1_locations_get"];
        put?: never;
        /** Create Location */
        post: operations["create_location_api_v1_locations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/studios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Studios
         * @description §18.3's studio list, M1's subset: the rows, not the health chips (C4 -- M9 owns
         *     those, and the operations board with them).
         */
        get: operations["get_studios_api_v1_platform_studios_get"];
        put?: never;
        /**
         * Create Studio
         * @description §5.1 -- 'Studios are provisioned by the platform operator, never self-created.
         *     There is no צור סטודיו button anywhere in the staff app.'
         */
        post: operations["create_studio_api_v1_platform_studios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/studios/{studio_id}/invite-owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Owner Invitation
         * @description §5.1 -- 'and sends an invitation to the person who will be its owner.'
         *
         *     The token comes back in this response and nowhere else, ever. Only its hash is stored.
         */
        post: operations["create_owner_invitation_api_v1_platform_studios__studio_id__invite_owner_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/studios/{studio_id}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suspend
         * @description §18.3's suspend action. A suspended studio disappears from every switcher, because
         *     `studios_for_identity` skips a non-active one.
         */
        post: operations["suspend_api_v1_platform_studios__studio_id__suspend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Setup */
        get: operations["read_setup_api_v1_setup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dismiss Setup
         * @description §5.1's exit at step 6. Stops auto-routing; says nothing about completeness.
         */
        post: operations["dismiss_setup_api_v1_setup_dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/steps/{step_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Step */
        patch: operations["update_step_api_v1_setup_steps__step_id__patch"];
        trace?: never;
    };
    "/api/v1/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Staff */
        get: operations["list_staff_api_v1_staff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Studio
         * @description Every staff role. Rendering the club's own name and logo is not a settings read in
         *     the §3.2 sense, and a coach app that could not do it would be enforcing a rule about
         *     writes by breaking a read.
         */
        get: operations["read_studio_api_v1_studio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Studio
         * @description The wizard's step 1 (פרטי מועדון) and the dashboard's הגדרות panel write through
         *     the same route -- there is one studio row and it should have one writer.
         *
         *     `exclude_unset` and not `exclude_none`: the two differ for a field a client sends
         *     explicitly as null, and treating "not mentioned" and "cleared" alike would make the
         *     הגדרות autosave blank every field it did not happen to include.
         */
        patch: operations["update_studio_api_v1_studio_patch"];
        trace?: never;
    };
    "/api/v1/studio/logo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Logo
         * @description Any signed-in member of the studio, coaches and guardians included.
         *
         *     Reading is not a settings write. A staff app that could not render the club's own logo
         *     would be enforcing a rule about writes by breaking a read.
         */
        get: operations["read_logo_api_v1_studio_logo_get"];
        put?: never;
        /** Upload Logo */
        post: operations["upload_logo_api_v1_studio_logo_post"];
        /**
         * Delete Logo
         * @description Idempotent -- a DELETE on a studio with no logo is a 204, not a 404.
         */
        delete: operations["delete_logo_api_v1_studio_logo_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AcceptInvitationRequest
         * @description §6.1 step 3's `[ יש לי קוד הזמנה ]` branch.
         *
         *     The callback already accepts an `invitation_token`, but that only helps someone who
         *     has the code BEFORE they sign in. A parent whose email differs from the invitation by
         *     one character signs in successfully, matches nothing, and needs a way forward that is
         *     not "sign out and start again with a code you were not told to keep".
         */
        AcceptInvitationRequest: {
            /** Token */
            token: string;
        };
        /**
         * AppAccessOut
         * @description §6.1's two queries, as the client sees them.
         *
         *     Two booleans and nothing else. A count of students or studios in the *other* app
         *     would leak what §6.1 says neither refusal screen may: "Neither screen leaks whether
         *     the account exists in the other app."
         */
        AppAccessOut: {
            /** Parent */
            parent: boolean;
            /** Staff */
            staff: boolean;
        };
        /** Body_upload_logo_api_v1_studio_logo_post */
        Body_upload_logo_api_v1_studio_logo_post: {
            /**
             * File
             * @description PNG, JPEG or WebP. Never SVG.
             */
            file: string;
        };
        /** CallbackRequest */
        CallbackRequest: {
            /** Code */
            code: string;
            /** Invitation Token */
            invitation_token?: string | null;
            /** State */
            state: string;
        };
        /** ClassCreate */
        ClassCreate: {
            /** Color */
            color?: string | null;
            /** Description */
            description?: string | null;
            /** Discipline */
            discipline?: string | null;
            /** Name */
            name: string;
        };
        /** ClassListResponse */
        ClassListResponse: {
            /** Items */
            items: components["schemas"]["ClassOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** ClassOut */
        ClassOut: {
            /** Color */
            color: string | null;
            /** Description */
            description: string | null;
            /** Discipline */
            discipline: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
        };
        /** GroupCreate */
        GroupCreate: {
            /** Age Max */
            age_max?: number | null;
            /** Age Min */
            age_min?: number | null;
            /**
             * Class Id
             * Format: uuid
             */
            class_id: string;
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
        };
        /** GroupListResponse */
        GroupListResponse: {
            /** Items */
            items: components["schemas"]["GroupOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** GroupOut */
        GroupOut: {
            /** Age Max */
            age_max: number | null;
            /** Age Min */
            age_min: number | null;
            /**
             * Class Id
             * Format: uuid
             */
            class_id: string;
            /** Description */
            description: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
        };
        /** GroupStaffCreate */
        GroupStaffCreate: {
            /** From Date */
            from_date?: string | null;
            /**
             * Person Id
             * Format: uuid
             */
            person_id: string;
            /** Role */
            role: string;
        };
        /** GroupStaffListResponse */
        GroupStaffListResponse: {
            /** Items */
            items: components["schemas"]["GroupStaffOut"][];
        };
        /** GroupStaffOut */
        GroupStaffOut: {
            /**
             * From Date
             * Format: date
             */
            from_date: string;
            /**
             * Group Id
             * Format: uuid
             */
            group_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Person Id
             * Format: uuid
             */
            person_id: string;
            /** Role */
            role: string;
            /** To Date */
            to_date: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Env
             * @enum {string}
             */
            env: "development" | "staging" | "production" | "test";
            /** Revision */
            revision: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
        };
        /** HealthTemplateListResponse */
        HealthTemplateListResponse: {
            /** Items */
            items: components["schemas"]["HealthTemplateOut"][];
        };
        /**
         * HealthTemplateOut
         * @description Conflict C3. The questions, never an answer -- M4 owns anything that could hold
         *     one.
         */
        HealthTemplateOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Version */
            version: number;
        };
        /**
         * InvitationOut
         * @description §5.3's token, returned exactly once.
         *
         *     Only its SHA-256 is stored, so nothing can reproduce this value later -- which is why
         *     the list endpoint has no field for it and why a re-send has to issue a new one.
         */
        InvitationOut: {
            /** Email */
            email: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Token */
            token: string;
        };
        /** InviteOwnerRequest */
        InviteOwnerRequest: {
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
        };
        /** LocationCreate */
        LocationCreate: {
            /** Address */
            address?: string | null;
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
        };
        /** LocationListResponse */
        LocationListResponse: {
            /** Items */
            items: components["schemas"]["LocationOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** LocationOut */
        LocationOut: {
            /** Address */
            address: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Notes */
            notes: string | null;
        };
        /** MeResponse */
        MeResponse: {
            access: components["schemas"]["AppAccessOut"];
            /** Acting As Person Id */
            acting_as_person_id: string | null;
            /** Active Studio Id */
            active_studio_id: string | null;
            /** Dev Tools */
            dev_tools: boolean;
            /**
             * Identity Id
             * Format: uuid
             */
            identity_id: string;
            /** Studios */
            studios: components["schemas"]["StudioMembershipOut"][];
        };
        /** ProviderListResponse */
        ProviderListResponse: {
            /** Items */
            items: components["schemas"]["ProviderOut"][];
        };
        /**
         * ProviderOut
         * @description One sign-in button the client may render.
         *
         *     Only configured providers are listed (app/services/identity/providers.py). A button
         *     for a provider whose credentials are absent fails one step *after* the user has
         *     picked their account, which is worse than a button that is not there.
         */
        ProviderOut: {
            /** Name */
            name: string;
            /** Start Url */
            start_url: string;
        };
        /** ProvisionStudioRequest */
        ProvisionStudioRequest: {
            /**
             * Default Locale
             * @default he
             */
            default_locale: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Timezone
             * @default Asia/Jerusalem
             */
            timezone: string;
        };
        /**
         * SessionResponse
         * @description The access token lives in the body, never in a cookie (§10.3).
         *
         *     The client holds it in memory and replays it, which is what keeps it out of
         *     automatic-credential territory -- a cookie-borne access token is sent by the browser
         *     on every request, which is what makes CSRF possible at all. The refresh token is in
         *     the Set-Cookie header and never here.
         */
        SessionResponse: {
            access: components["schemas"]["AppAccessOut"];
            /** Access Token */
            access_token: string;
            /** Active Studio Id */
            active_studio_id: string | null;
            /** Expires In */
            expires_in: number;
            /** Studios */
            studios: components["schemas"]["StudioMembershipOut"][];
        };
        /**
         * SetupProgressOut
         * @description What all three setup routes return, so a caller never has to re-fetch.
         *
         *     `complete` and `dismissed_at` are separate on purpose -- SPEC §5.1 states two
         *     different things and app/services/structure/setup.py carries the reasoning.
         */
        SetupProgressOut: {
            /**
             * Complete
             * @description Every one of the six steps is done.
             */
            complete: boolean;
            /**
             * Dismissed At
             * @description The owner chose an exit at step 6. Auto-routing stops.
             */
            dismissed_at?: string | null;
            /** Steps */
            steps: components["schemas"]["SetupStepOut"][];
        };
        /** SetupStepIn */
        SetupStepIn: {
            /**
             * Status
             * @enum {string}
             */
            status: "done" | "skipped";
        };
        /** SetupStepOut */
        SetupStepOut: {
            /** At */
            at?: string | null;
            /** Id */
            id: string;
            /** Order */
            order: number;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "done" | "skipped";
        };
        /** StaffGroupOut */
        StaffGroupOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** StaffListResponse */
        StaffListResponse: {
            /**
             * Groups Without Coach
             * @description 3d's banner, at the resolution M1 can answer. It draws 'sessions this week with no coach', which needs materialised sessions; W2's SCHEDULE lane sharpens this to that.
             */
            groups_without_coach: components["schemas"]["StaffGroupOut"][];
            /** Items */
            items: components["schemas"]["StaffMemberOut"][];
        };
        /** StaffMemberOut */
        StaffMemberOut: {
            /** Email */
            email?: string | null;
            /** First Name */
            first_name?: string | null;
            /** Groups */
            groups: components["schemas"]["StaffGroupOut"][];
            /** Last Name */
            last_name?: string | null;
            /** Permissions */
            permissions: string[];
            /** Person Id */
            person_id?: string | null;
            /** Roles */
            roles: string[];
            /** Status */
            status: string;
            /**
             * Weekly Hours
             * @description Always null in M1. Weekly load is group_schedule_rule × session, both W2 contract models. Zero would report an idle coach rather than a missing measurement.
             */
            weekly_hours?: number | null;
        };
        /** StudioListResponse */
        StudioListResponse: {
            /** Items */
            items: components["schemas"]["app__schemas__platform__StudioOut"][];
        };
        /**
         * StudioLogoOut
         * @description What POST /studio/logo returns.
         *
         *     A URL and not a key. The key is an internal address no client should learn, let alone
         *     send back -- §2.5 constructs every key server-side precisely so that no request ever
         *     carries one.
         */
        StudioLogoOut: {
            /**
             * Logo Url
             * @description The scoped read route, cache-busted by updated_at.
             */
            logo_url: string;
        };
        /** StudioMembershipOut */
        StudioMembershipOut: {
            /** Is Guardian */
            is_guardian: boolean;
            /**
             * Person Id
             * Format: uuid
             */
            person_id: string;
            /** Roles */
            roles: string[];
            /**
             * Studio Id
             * Format: uuid
             */
            studio_id: string;
            /** Studio Is Demo */
            studio_is_demo: boolean;
            /** Studio Name */
            studio_name: string;
        };
        /**
         * StudioUpdate
         * @description Every field optional -- the wizard writes what the owner filled in, and the
         *     הגדרות panel autosaves one field at a time. `exclude_unset` in the router is what
         *     turns that into a partial write rather than a blanking one.
         */
        StudioUpdate: {
            /** Address */
            address?: string | null;
            /** Name */
            name?: string | null;
            /** Parent Locales */
            parent_locales?: string[] | null;
            /** Phone */
            phone?: string | null;
            /** Sport */
            sport?: string | null;
        };
        /** SwitchStudioRequest */
        SwitchStudioRequest: {
            /**
             * Studio Id
             * Format: uuid
             */
            studio_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** StudioOut */
        app__schemas__platform__StudioOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By Identity Id */
            created_by_identity_id: string | null;
            /** Default Locale */
            default_locale: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Demo */
            is_demo: boolean;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Status */
            status: string;
            /** Timezone */
            timezone: string;
        };
        /**
         * StudioOut
         * @description The merged column-and-settings view both the wizard's step 1 and the dashboard's
         *     הגדרות panel read.
         */
        app__schemas__studio__StudioOut: {
            /** Address */
            address?: string | null;
            /** Default Locale */
            default_locale: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Logo Url */
            logo_url?: string | null;
            /** Name */
            name: string;
            /** Parent Locales */
            parent_locales: string[];
            /** Phone */
            phone?: string | null;
            /** Slug */
            slug: string;
            /** Sport */
            sport?: string | null;
            /** Timezone */
            timezone: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    accept_invitation_code_api_v1_auth_accept_invitation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInvitationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_providers_api_v1_auth_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderListResponse"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    switch_studio_api_v1_auth_switch_studio_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchStudioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    callback_api_v1_auth__provider__callback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CallbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_api_v1_auth__provider__start_get: {
        parameters: {
            query?: {
                app?: string;
                return_path?: string;
            };
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_classes_api_v1_classes_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_class_api_v1_classes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_groups_api_v1_groups_get: {
        parameters: {
            query?: {
                class_id?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_group_api_v1_groups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_group_staff_api_v1_groups__group_id__staff_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupStaffListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_group_staff_api_v1_groups__group_id__staff_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupStaffCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupStaffOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_health_templates_api_v1_health_templates_get: {
        parameters: {
            query?: {
                kind?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthTemplateListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_locations_api_v1_locations_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_location_api_v1_locations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_studios_api_v1_platform_studios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudioListResponse"];
                };
            };
        };
    };
    create_studio_api_v1_platform_studios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProvisionStudioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__schemas__platform__StudioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_owner_invitation_api_v1_platform_studios__studio_id__invite_owner_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studio_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteOwnerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suspend_api_v1_platform_studios__studio_id__suspend_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__schemas__platform__StudioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_setup_api_v1_setup_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupProgressOut"];
                };
            };
        };
    };
    dismiss_setup_api_v1_setup_dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupProgressOut"];
                };
            };
        };
    };
    update_step_api_v1_setup_steps__step_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                step_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupStepIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupProgressOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_staff_api_v1_staff_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffListResponse"];
                };
            };
        };
    };
    read_studio_api_v1_studio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__schemas__studio__StudioOut"];
                };
            };
        };
    };
    update_studio_api_v1_studio_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudioUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__schemas__studio__StudioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_logo_api_v1_studio_logo_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    upload_logo_api_v1_studio_logo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_logo_api_v1_studio_logo_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudioLogoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_logo_api_v1_studio_logo_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
