import { chromium } from '@playwright/test'
const OUT = process.argv[2]
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--no-sandbox'] })
const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 }, locale: 'he-IL' })
const p = await ctx.newPage()
await p.goto(`http://localhost:5175/api/v1/dev/sign-in-as/manager?app=dashboard&return_path=${encodeURIComponent('/#/home')}`)
await p.waitForLoadState('networkidle'); await p.waitForTimeout(2500)
await p.screenshot({ path: `${OUT}/9-dash-home.png`, fullPage: true })
await p.goto('http://localhost:5175/#/billing'); await p.waitForTimeout(3000)
await p.screenshot({ path: `${OUT}/10-dash-billing.png`, fullPage: true })
await p.goto('http://localhost:5175/#/students'); await p.waitForTimeout(2500)
await p.locator('select').filter({ has: p.locator('option[value="no_contact"]') }).selectOption('no_contact')
await p.waitForTimeout(2000)
await p.locator('[data-testid="students-table"] tbody button').first().click()
await p.waitForTimeout(2000)
await p.getByTestId('detail-tab-finance').click(); await p.waitForTimeout(2000)
await p.screenshot({ path: `${OUT}/11-dash-card-finance.png` })
await p.getByTestId('detail-tab-training').click(); await p.waitForTimeout(1500)
await p.screenshot({ path: `${OUT}/12-dash-card-training.png` })
await browser.close()
